committee_data = [
    {"name": "Albrecht Schmidt", "affiliation": "LMU Munich"},
    {"name": "Kaisa Väänänen", "affiliation": "Tampere University"},
    {"name": "Tesh Goyal", "affiliation": "Google Research"},
    {"name": "Per Ola Kristensson", "affiliation": "University of Cambridge"},
    {"name": "Anicia Peters", "affiliation": "University of Namibia"},
    {"name": "Stefanie Mueller", "affiliation": "Massachusetts Institute of Technology"},
    {"name": "Julie R. Williamson", "affiliation": "University of Glasgow"},
    {"name": "Max L. Wilson", "affiliation": "University of Nottingham"},
    {"name": "Alisa Burova", "affiliation": "Tampere University"},
    {"name": "Passant Elagroudy", "affiliation": "German Centre for Artificial Intelligence (DFKI)"},
    {"name": "Jie Cai", "affiliation": "Penn State University"},
    {"name": "Gionnieve Lim", "affiliation": "Singapore University of Technology and Design"},
    {"name": "Andrii Matviienko", "affiliation": "Technical University of Darmstadt"},
    {"name": "Callum Berger", "affiliation": "University of Nottingham"},
    {"name": "Faraz Faruqi", "affiliation": "Massachusetts Institute of Technology"},
    {"name": "Megan Hofmann", "affiliation": "Northeastern University"},
    {"name": "Yue Jiang", "affiliation": "Aalto University"},
    {"name": "Claudia Loitsch", "affiliation": "TU Dresden"},
    {"name": "Benjamin Tannert", "affiliation": "City University of Applied Sciences Bremen"},
    {"name": "Matthew Louis Mauriello", "affiliation": "University of Delaware"},
    {"name": "Gözel Shakeri", "affiliation": "Carl von Ossietzky University of Oldenburg"},
    {"name": "Jonah-Noël Kaiser", "affiliation": "Carl von Ossietzky University of Oldenburg"},
    {"name": "Thu Marianski", "affiliation": "Carl von Ossietzky University of Oldenburg"},
    {"name": "Sven Mayer", "affiliation": "LMU Munich"},
    {"name": "Fiona Draxler", "affiliation": "LMU Munich"},
    {"name": "Julian Frommel", "affiliation": "Utrecht University"},
    {"name": "Thomas Kosch", "affiliation": "Utrecht University"},
    {"name": "Alexander G. Mirnig", "affiliation": "University of Salzburg"},
    {"name": "Diego Muñoz", "affiliation": "Swinburne University of Technology"},
    {"name": "Raphael Wimmer", "affiliation": "University of Regensburg"},
    {"name": "Frank Bentley", "affiliation": "Google"},
    {"name": "Abiodun Ogunyemi", "affiliation": "Tallinn University"},
    {"name": "Eunice Sari", "affiliation": "UX Indonesia"},
    {"name": "Daniela Busse", "affiliation": "Meta"},
    {"name": "Bastian Pfleging", "affiliation": "TU Bergakademie Freiberg"},
    {"name": "Margaret Burnett", "affiliation": "Oregon State University"},
    {"name": "Kasper Hornbæk", "affiliation": "University of Copenhagen"},
    {"name": "Bradley Rey", "affiliation": "University of British Columbia"},
    {"name": "Lars Erik Holmquist", "affiliation": "Northumbria University"},
    {"name": "Jaeyeon Lee", "affiliation": "Ulsan National Institute of Science and Technology"},
    {"name": "David Lindlbauer", "affiliation": "Carnegie Mellon University"},
    {"name": "Yomna Abdelrahmen", "affiliation": "Bundeswehr University Munich"},
    {"name": "Anirudha Joshi", "affiliation": "Indian Institute of Technology Bombay"},
    {"name": "Cosmin Munteanu", "affiliation": "University of Waterloo"},
    {"name": "Tanja Döring", "affiliation": "University of Bremen"},
    {"name": "Frank Steinicke", "affiliation": "Universität Hamburg"},
    {"name": "Julian Rasch", "affiliation": "LMU Munich"},
    {"name": "Oliver Haimson", "affiliation": "University of Michigan"},
    {"name": "Shaimaa Lazem", "affiliation": "City of Scientific Research and Technological Applications (SRTA-City)"},
    {"name": "Abdallah El Ali", "affiliation": "Centrum Wiskunde & Informatica (CWI)"},
    {"name": "Vinoba Vinayagamoorthy", "affiliation": "Samsung"},
    {"name": "Anke Brock", "affiliation": "ENAC, Université Toulouse"},
    {"name": "Jessica Cauchard", "affiliation": "Ben Gurion University of the Negev"},
    {"name": "Mario Alberto Moreno Rocha", "affiliation": "Universidad Tecnológica de la Mixteca"},
    {"name": "Niels Henze", "affiliation": "University of Regensburg"},
    {"name": "Jakob Karolus", "affiliation": "German Research Center for Artificial Intelligence (DFKI)"},
    {"name": "Ville Mäkelä", "affiliation": "University of Waterloo"},
    {"name": "Christian Sturm", "affiliation": "Technische Hochschule Ingolstadt"},
    {"name": "Chat Wacharamanotham", "affiliation": "Swansea University"},
    {"name": "Ciabhan Connely", "affiliation": "Georgia Institute of Technology"},
    {"name": "Julia Dunbar", "affiliation": "University of Washington"},
    {"name": "Maximiliane Windl", "affiliation": "LMU Munich"},
    {"name": "John Wenskovitch", "affiliation": "Pacific Northwest National Laboratory"},
    {"name": "Johannes Zagermann", "affiliation": "University of Konstanz"},
    {"name": "Thomas Olsson", "affiliation": "Tampere University"},
    {"name": "Dakuo Wang", "affiliation": "Northeastern University"},
    {"name": "Heike Winschiers-Theophilus", "affiliation": "Namibia University of Science and Technology"},
    {"name": "Lynne Baillie", "affiliation": "Heriot-Watt University"},
    {"name": "Wilko Heuten", "affiliation": "OFFIS – Institute for IT"},
    {"name": "Maryam Mustafa", "affiliation": "Lahore University of Management"},
    {"name": "Tawfiq Ammari", "affiliation": "Rutgers University School of Communication and Information"},
    {"name": "Anna Maria Feit", "affiliation": "Saarland University"},
    {"name": "Heloisa de Souza Pereira Candello", "affiliation": "IBM Brazil"},
    {"name": "Amon Rapp", "affiliation": "University of Torino"},
    {"name": "Rob Comber", "affiliation": "KTH Royal Institute of Technology"},
    {"name": "Konstantinos Koumaditis", "affiliation": "Aarhus University"},
    {"name": "Yi Chi Liao", "affiliation": "Aalto University"},
    {"name": "Christina Zaga", "affiliation": "University of Twente"},
    {"name": "Carol Klyver", "affiliation": "Foundations of Excellence"},
    {"name": "Elizabeth Churchill", "affiliation": "Google"},
    {"name": "Christine Bauer", "affiliation": "Utrecht University"},
    {"name": "Siobahn Day Grady", "affiliation": "North Carolina Central University"},
    {"name": "Anouk van Kasteren", "affiliation": "Utrecht University"},
    {"name": "Jordan Deja", "affiliation": "University of Primorska"},
    {"name": "Cuauhtémoc Rivera Loaiza", "affiliation": "Universidad Michoacana"},
    {"name": "Marisol Wong-Villacres", "affiliation": "Escuela Superior Politécnica del Litoral"},
    {"name": "João Moreira", "affiliation": "INESC-ID: Instituto de Engenharia de Sistemas e Computadores, Investigação e Desenvolvimento em Lisboa"}
]

committee_data_1 = [
    {"name": "Cliff Lampe", "affiliation": "University of Michigan"},
    {"name": "Simone Barbosa", "affiliation": "PUC-Rio"},
    {"name": "David A. Shamma", "affiliation": "Toyota Research Institute"},
    {"name": "Caroline Appert", "affiliation": "Université Paris-Saclay"},
    {"name": "Katta Spiel", "affiliation": "TU Wien"},
    {"name": "Christina Harrington", "affiliation": "Carnegie Mellon University"},
    {"name": "Danilo Gasques", "affiliation": "UC San Diego"},
    {"name": "Ihudiya Finda Williams", "affiliation": "University of Michigan"},
    {"name": "Monica Pereira", "affiliation": "Brunel University London"},
    {"name": "Dominic DiFranzo", "affiliation": "Lehigh University"},
    {"name": "Hugo Romat", "affiliation": "Microsoft"},
    {"name": "Anupriya Tuli", "affiliation": "IIIT Delhi, India"},
    {"name": "Cayley MacArthur", "affiliation": "University of Waterloo, Canada"},
    {"name": "Steven Drucker", "affiliation": "Microsoft Research"},
    {"name": "Julie Williamson", "affiliation": "University of Glasgow"},
    {"name": "Koji Yatani", "affiliation": "University of Tokyo"},
    {"name": "Nikita Samarin", "affiliation": "University of California, Berkeley"},
    {"name": "Zhongyi Zhou", "affiliation": "University of Tokyo"},
    {"name": "David Lindlbauer", "affiliation": "CMU"},
    {"name": "Heloisa Candello", "affiliation": "IBM"},
    {"name": "Vinoba Vinayagamoorthy", "affiliation": "BBC"},
    {"name": "Pedro Lopes", "affiliation": "University of Chicago"},
    {"name": "Frank Bentley", "affiliation": "Google"},
    {"name": "Catherine Letondal", "affiliation": "Ecole Nationale Aviation Civile"},
    {"name": "Anicia Peters", "affiliation": "University of Namibia"},
    {"name": "Kathryn Ringland", "affiliation": "University of California"},
    {"name": "Norman Makoto Su", "affiliation": "University of California, Santa Cruz"},
    {"name": "Oliver Haimson", "affiliation": "University of Michigan"},
    {"name": "Nicolai Marquardt", "affiliation": "University College London"},
    {"name": "Eunice Sari", "affiliation": "UX Indonesia"},
    {"name": "Louise Barkhuus", "affiliation": "IT University of Copenhagen"},
    {"name": "Shaimaa Lazem", "affiliation": "City for Scientific Research and Technological Applications"},
    {"name": "Simon Perrault", "affiliation": "Singapore University of Technology and Design"},
    {"name": "Kashyap Todi", "affiliation": "Facebook Reality Labs"},
    {"name": "Pablo Cesar", "affiliation": "CWI"},
    {"name": "Stephanie Jordan", "affiliation": "Michigan State University"},
    {"name": "Makayla Lewis", "affiliation": "Kingston University London"},
    {"name": "Sameer Patil", "affiliation": "University of Utah"},
    {"name": "Cynthia Bennett", "affiliation": "CMU"},
    {"name": "Nova Ahmed", "affiliation": "North South University"},
    {"name": "Maryam Mustafa", "affiliation": "Lahore University of Management Sciences"},
    {"name": "Anusha Withana", "affiliation": "The University of Sydney"},
    {"name": "Pei-Yi (Patricia) Kuo", "affiliation": "National Tsing Hua University"},
    {"name": "Z Toups", "affiliation": "New Mexico State University"},
    {"name": "Jakob Karolus", "affiliation": "LMU Munich"},
    {"name": "Vicky McArthur", "affiliation": "Carleton University"},
    {"name": "Jasmine Jones", "affiliation": "Berea College"},
    {"name": "Can Liu", "affiliation": "City University of Hong Kong"},
    {"name": "Jorge Goncalves", "affiliation": "University of Melbourne, Australia"},
    {"name": "Dakuo Wang", "affiliation": "IBM"},
    {"name": "Sheena Erete", "affiliation": "DePaul University"},
    {"name": "Rita Orji", "affiliation": "Dalhousie University"},
    {"name": "Raimund Dachselt", "affiliation": "Technische Universität Dresden"},
    {"name": "Melissa Densmore", "affiliation": "University of Cape Town"},
    {"name": "Julie Kientz", "affiliation": "University of Washington"},
    {"name": "Eva Hornecker", "affiliation": "Bauhaus-Universität Weimar"},
    {"name": "Nathalie Riche", "affiliation": "Microsoft Research"},
    {"name": "Casey Fiesler", "affiliation": "University of Colorado Boulder"},
    {"name": "Jude Yew", "affiliation": "Google"},
    {"name": "Max Van Kleek", "affiliation": "University of Oxford"},
    {"name": "Fanny Chevalier", "affiliation": "University of Toronto"},
    {"name": "Carrie Cai", "affiliation": "Google"},
    {"name": "Emmanuel Pietriga", "affiliation": "Inria"},
    {"name": "Paula Lago", "affiliation": "Concordia University"},
    {"name": "Vanessa Peña-Araya", "affiliation": "Inria"},
    {"name": "Sven Mayer", "affiliation": "LMU Munich"},
    {"name": "Thomas Kosch", "affiliation": "TU Darmstadt"},
    {"name": "Raphael Wimmer", "affiliation": "University of Regensburg"},
    {"name": "Diego Muñoz", "affiliation": "Swinburne University of Technology"},
    {"name": "Alexander Mirnig", "affiliation": "University of Salzburg"},
    {"name": "Anhong Guo", "affiliation": "University of Michigan"},
    {"name": "Rob Comber", "affiliation": "KTH"},
    {"name": "Cristina Zaga", "affiliation": "University of Twente, Design Lab"},
    {"name": "Yi-Chi Liao", "affiliation": "Aalto University"},
    {"name": "Bingjie Yu", "affiliation": "NetEase"},
    {"name": "Ciabhan Connely", "affiliation": "Georgia Tech"},
    {"name": "Julia Dunbar", "affiliation": "University of Washington"},
    {"name": "Pranjal Jain", "affiliation": "theUXWhale, India"},
    {"name": "Emeline Brulé", "affiliation": "University of Sussex"},
    {"name": "Simone Kriglstein", "affiliation": "University of Vienna & AIT Austrian Institute of Technology GmbH"},
    {"name": "John Wenskovitch", "affiliation": "Pacific Northwest National Laboratory"},
    {"name": "Toni-Jan Keith Monserrat", "affiliation": "University of the Philippines Los Banos"},
    {"name": "Jie Li", "affiliation": "CWI"},
    {"name": "Dhruv Jain", "affiliation": "University of Washington"},
    {"name": "Garreth Tigwell", "affiliation": "Rochester Institute of Technology"},
    {"name": "Zainab AlMeraj", "affiliation": "Kuwait University"},
    {"name": "Kotaro Hara", "affiliation": "Singapore Management University"},
    {"name": "Venkatesh Potluri", "affiliation": "University of Washington"},
    {"name": "Shercole K.", "affiliation": "VIA LINK"},
    {"name": "Jaelle Scheuerman", "affiliation": "U.S. Naval Research Laboratory"},
    {"name": "Minha Lee", "affiliation": "Eindhoven University of Technology"},
    {"name": "Patrick Gage Kelley", "affiliation": "Google"},
    {"name": "Rua Williams", "affiliation": "Purdue University"},
    {"name": "Gopinaath Kannabiran", "affiliation": "IT University of Copenhagen"},
    {"name": "Siobahn Day Grady", "affiliation": "North Carolina Central University"},
    {"name": "Rina Wehbe", "affiliation": "University of Waterloo"},
    {"name": "Cale Passmore", "affiliation": "University of Saskatchewan"},
    {"name": "Christine Bauer", "affiliation": "Utrecht University"},
    {"name": "Annu Sible Prabhakar", "affiliation": "University of Cincinnati"},
    {"name": "Cuauhtémoc Rivera Loaiza", "affiliation": "Universidad Michoacana de San Nicolás de Hidalgo"},
    {"name": "Eiad Yafi", "affiliation": "University of Technology Sydney & Institute of Business, Timor-Leste"},
    {"name": "Susan Dray", "affiliation": "Dray & Associates"},
    {"name": "Marisol Wong-Villacres", "affiliation": "Georgia Tech"},
    {"name": "Parisa Eslambolchilar", "affiliation": "University of Cardiff"},
    {"name": "Kristin Williams", "affiliation": "CMU"},
    {"name": "Pedro Reynolds-Cuéllar", "affiliation": "MIT Media Lab"},
    {"name": "Jason Jacques", "affiliation": "University of Cambridge"},
]

chairs_2 = [
    {"name": "Yoshifumi Kitamura", "affiliation": "Tohoku University"},
    {"name": "Aaron Quigley", "affiliation": "University of New South Wales, Australia"},
    {"name": "Kaori Ikematsu", "affiliation": "Yahoo Japan Corporation"},
    {"name": "Thomas Kosch", "affiliation": "TU Darmstadt"},
    {"name": "Katherine Isbister", "affiliation": "University of California Santa Cruz"},
    {"name": "Takeo Igarashi", "affiliation": "The University of Tokyo"},
    {"name": "Yuki Koyama", "affiliation": "National Institute of Advanced Industrial Science and Technology (AIST)"},
    {"name": "Elena Márquez Segura", "affiliation": "Universidad Carlos III de Madrid"},
    {"name": "Pernille Bjørn", "affiliation": "University of Copenhagen"},
    {"name": "Steven Drucker", "affiliation": "Microsoft Research"},
    {"name": "Claudine Tinsman", "affiliation": "University of Oxford"},
    {"name": "Earl Huff", "affiliation": "Clemson University"},
    {"name": "Danielle Wilde", "affiliation": "University of Southern Denmark"},
    {"name": "Nova Ahmed", "affiliation": "North South University, Bangladesh"},
    {"name": "Pierre Dragicevic", "affiliation": "Inria, France"},
    {"name": "Haley MacLeod", "affiliation": "Facebook"},
    {"name": "Stefan Manojlovic", "affiliation": "TomTom"},
    {"name": "Carine Lallemand", "affiliation": "Eindhoven University of Technology"},
    {"name": "Antti Oulasvirta", "affiliation": "Aalto University"},
    {"name": "Pedro Lopes", "affiliation": "University of Chicago"},
    {"name": "Sylvain Malacria", "affiliation": "Inria, France"},
    {"name": "Yuta Sugiura", "affiliation": "Keio University"},
    {"name": "Yang Li", "affiliation": "Google Research"},
    {"name": "Wendy Mackay", "affiliation": "Inria, Université Paris-Saclay"},
    {"name": "Wendy Ju", "affiliation": "Cornell Tech"},
    {"name": "Leah Findlater", "affiliation": "University of Washington"},
    {"name": "Edward Melcer", "affiliation": "University of California, Santa Cruz"},
    {"name": "Katrin Wolf", "affiliation": "Beuth University of Applied Sciences Berlin"},
    {"name": "Juho Kim", "affiliation": "KAIST"},
    {"name": "Leila Takayama", "affiliation": "University of California, Santa Cruz"},
    {"name": "Dan Russell", "affiliation": "Google"},
    {"name": "Germán Leiva", "affiliation": "Aarhus University"},
    {"name": "Emeline Brulé", "affiliation": "University of Sussex"},
    {"name": "Jofish Kaye", "affiliation": "Mozilla"},
    {"name": "Hideaki Kuzuoka", "affiliation": "The University of Tokyo"},
    {"name": "Jun Kato", "affiliation": "National Institute of Advanced Industrial Science and Technology (AIST) & Arch Inc., Japan"},
    {"name": "Nolwenn Maudet", "affiliation": "University of Strasbourg"}
]

chairs_2020 = [
    {"name": "Regina Bernhaupt", "affiliation": "Eindhoven University of Technology, Netherlands"},
    {"name": "Florian 'Floyd' Mueller", "affiliation": "Monash University, Melbourne, Australia"},
    {"name": "David Verweij", "affiliation": "Open Lab, Newcastle University, Newcastle, UK"},
    {"name": "Josh Andres", "affiliation": "IBM Research & Exertion Games Lab RMIT, Melbourne, Australia"},
    {"name": "Joanna McGrenere", "affiliation": "University of British Columbia, Vancouver, Canada"},
    {"name": "Andy Cockburn", "affiliation": "University of Canterbury, Christchurch, New Zealand"},
    {"name": "Ignacio (Nacho) Avellino", "affiliation": "University of Maryland Baltimore County, MD, USA"},
    {"name": "Alix Goguey", "affiliation": "Grenoble Alpes University, Grenoble, France"},
    {"name": "Pernille Bjorn", "affiliation": "University of Copenhagen, Copenhagen, Denmark"},
    {"name": "Shengdong Zhao", "affiliation": "National University of Singapore, Singapore"},
    {"name": "Briane Paul Samson", "affiliation": "Future University Hakodate, Japan"},
    {"name": "Rafal Kocielnik", "affiliation": "University of Washington, Seattle, USA"},
    {"name": "Ann Light", "affiliation": "University of Sussex, UK"},
    {"name": "Katta Spiel", "affiliation": "KU Leuven, Belgium"},
    {"name": "Danielle Wilde", "affiliation": "University of Southern Denmark, Denmark"},
    {"name": "Maja Vukovic", "affiliation": "IBM, Yorktown Heights, USA"},
    {"name": "Stefan Manojlovic", "affiliation": "Philips, Amsterdam, Netherlands"},
    {"name": "Daniela Busse", "affiliation": "eBay Inc., CA, USA"},
    {"name": "Rajan Vaish", "affiliation": "Snap Research, Santa Monica, USA"},
    {"name": "Ian Oakley", "affiliation": "Ulsan National Institute of Science and Technology, South Korea"},
    {"name": "Sylvain Malacria", "affiliation": "Inria, France"},
    {"name": "Walter Lasecki", "affiliation": "University of Michigan, Ann Arbor, USA"},
    {"name": "Koji Yatani", "affiliation": "University of Tokyo, Japan"},
    {"name": "Leah Findlater", "affiliation": "University of Washington, Seattle, USA"},
    {"name": "Duncan Brumby", "affiliation": "University College London, UK"},
    {"name": "Madeline Balaam", "affiliation": "KTH Royal Institute of Technology, Stockholm, Sweden"},
    {"name": "Neha Kumar", "affiliation": "Georgia Institute of Technology, Atlanta, USA"},
    {"name": "Stacey Kuznetsov", "affiliation": "Arizona State University, Tempe, USA"},
    {"name": "Jeni Paay", "affiliation": "Swinburne University of Technology, Melbourne, Australia"},
    {"name": "David Flatla", "affiliation": "University of Guelph, Canada"},
    {"name": "Zhanna Sarsenbayeva", "affiliation": "University of Melbourne, Australia"},
    {"name": "Carla Griggio", "affiliation": "The University of Tokyo, Japan"},
    {"name": "Jorge Goncalves", "affiliation": "University of Melbourne, Australia"},
    {"name": "Jonna Häkkilä", "affiliation": "University of Lapland, Rovaniemi, Finland"},
    {"name": "Katrin Wolf", "affiliation": "University of Hamburg, Germany"},
    {"name": "Bastian Pfleging", "affiliation": "Eindhoven University of Technology, Netherlands"},
    {"name": "Rob Comber", "affiliation": "KTH Royal Institute of Technology, Sweden"},
    {"name": "Mike Hazas", "affiliation": "Lancaster University, Lancashire, UK"},
    {"name": "Alexander Eiselmayer", "affiliation": "University of Zurich, Switzerland"},
    {"name": "Wanyu 'Abby' Liu", "affiliation": "IRCAM Centre Pompidou, Paris, France"},
    {"name": "Jessica Colnago", "affiliation": "Carnegie Mellon University, USA"},
    {"name": "Nicole Sultanum", "affiliation": "University of Toronto, Canada"},
    {"name": "Duncan Brumby", "affiliation": "University College London, UK"},
    {"name": "Tovi Grossman", "affiliation": "University of Toronto, Canada"},
    {"name": "Parmit Chilana", "affiliation": "Simon Fraser University, Canada"},
    {"name": "Niels van Berkel", "affiliation": "Aalborg University, Denmark"},
    {"name": "Katarzyna (Kathy) Stawarz", "affiliation": "University of Bristol, UK"},
    {"name": "Tom Horak", "affiliation": "Technische Universität Dresden, Germany"},
    {"name": "Sven Mayer", "affiliation": "Carnegie Mellon University, PA, USA"},
    {"name": "Michael Stewart", "affiliation": "James Madison University, VA, USA"},
    {"name": "Sandy Gould", "affiliation": "University of Birmingham, United Kingdom"},
    {"name": "Rakesh Patibanda", "affiliation": "Exertion Games Lab, RMIT University, Australia"},
    {"name": "Lila Bozgeyikli", "affiliation": "University of Arizona, USA"},
    {"name": "Jeffrey Bardzell", "affiliation": "Indiana University, USA"},
    {"name": "Scott Robertson", "affiliation": "University of Hawai'i, Honolulu, Hawai'i, USA"},
    {"name": "Rick Kazman", "affiliation": "University of Hawai'i, Honolulu, Hawai'i, USA"},
    {"name": "Kyle Rector", "affiliation": "University of Iowa, USA"},
    {"name": "Shari Trewin", "affiliation": "IBM Research, Yorktown, USA"},
    {"name": "Juho Kim", "affiliation": "Korea Advanced Institute of Science and Technology, South Korea"},
    {"name": "Cristina Zaga", "affiliation": "University of Twente, Netherlands"},
    {"name": "Simone Kriglstein", "affiliation": "AIT Austrian Institute of Technology, Austria"},
    {"name": "Rina Wehbe", "affiliation": "University of Waterloo, Canada"},
    {"name": "Maria Wolters", "affiliation": "Alan Turing Institute, London, UK"},
    {"name": "Robin Brewer", "affiliation": "University of Michigan, Ann Arbor, USA"},
    {"name": "Jed Brubaker", "affiliation": "University of Colorado Boulder, USA"},
    {"name": "Roman Rädle", "affiliation": "Facebook, USA"},
    {"name": "David Lindlbauer", "affiliation": "ETH Zurich, Switzerland"},
    {"name": "Kashyap Todi", "affiliation": "Aalto University, Finland"},
    {"name": "Rohit Ashok Khot", "affiliation": "RMIT University, Australia"},
    {"name": "Elisa Mekler", "affiliation": "Aalto University, Finland"},
    {"name": "Dong-Bach Vo", "affiliation": "University of Glasgow, UK"},
    {"name": "Bill Hamilton", "affiliation": "New Mexico State University, USA"},
    {"name": "Renee Noortman", "affiliation": "Eindhoven University of Technology, Netherlands"},
    {"name": "David Verweij", "affiliation": "Newcastle University, UK"},
    {"name": "Adrian Friday", "affiliation": "Lancaster University, UK"},
    {"name": "Christian Remy", "affiliation": "Aarhus University, Denmark"},
    {"name": "Mike Hazas", "affiliation": "Lancaster University, Lancashire, UK"},
    {"name": "Samuel Mann", "affiliation": "Otago Polytechnic, New Zealand"},
    {"name": "Elisabeth Churchill", "affiliation": "Google, Mountain View, USA"},
    {"name": "Masa Inakage", "affiliation": "Keio University, Japan"},
    {"name": "Max van Kleek", "affiliation": "University of Oxford, UK"},
    {"name": "Suranga Nanayakkara", "affiliation": "University of Auckland, New Zealand"},
    {"name": "Anusha Withana", "affiliation": "The University of Sydney, Australia"},
    {"name": "Mingrui Ray Zhang", "affiliation": "University of Washington, USA"},
    {"name": "Steven Rick", "affiliation": "University of California San Diego, USA"},
    {"name": "Philippe Palanque", "affiliation": "Université Toulouse III Paul Sabatier, France"}
]

chairs_2019 = [
    {"name": "Anna Cox", "affiliation": "University College London, UK"},
    {"name": "Vassilis Kostakos", "affiliation": "University of Melbourne, Australia"},
    {"name": "Katarzyna Stawarz", "affiliation": "Bristol University, UK"},
    {"name": "Niels van Berkel", "affiliation": "University of Melbourne, Australia"},
    {"name": "Anind Dey", "affiliation": "University of Washington, US"},
    {"name": "Shengdong Zhao", "affiliation": "National University of Singapore, Singapore"},
    {"name": "Briane Paul V. Samson", "affiliation": "Future University Hakodate, Japan"},
    {"name": "Sonali R. Mishra", "affiliation": "University of Washington, US"},
    {"name": "Jorge Goncalves", "affiliation": "University of Melbourne, Australia"},
    {"name": "Sandy Gould", "affiliation": "University of Birmingham, UK"},
    {"name": "Xinru Page", "affiliation": "Bentley University, US"},
    {"name": "Graham Wilson", "affiliation": "University of Strathclyde, UK"},
    {"name": "Frank Vetere", "affiliation": "University of Melbourne, Australia"},
    {"name": "Katrin Wolf", "affiliation": "Hamburg University of Applied Sciences, Germany"},
    {"name": "Rob Comber", "affiliation": "RISE Research Institutes of Sweden, Sweden"},
    {"name": "Lindsay Reynolds", "affiliation": "Facebook, US"},
    {"name": "Katie A. Siek", "affiliation": "Indiana University, US"},
    {"name": "Nazanin Andalibi", "affiliation": "University of Michigan, US"},
    {"name": "Jessica Colnago", "affiliation": "Carnegie Mellon University, US"},
    {"name": "Haley MacLeod", "affiliation": "Indiana University, US"},
    {"name": "Tovi Grossman", "affiliation": "Autodesk Research, Canada"},
    {"name": "Frederik Brudy", "affiliation": "University College London, UK"},
    {"name": "Tom Horak", "affiliation": "TU Dresden, Germany"},
    {"name": "Danula Hettiachchi", "affiliation": "University of Melbourne, Australia"},
    {"name": "Duncan Brumby", "affiliation": "University College London, UK"},
    {"name": "Cosmin Munteanu", "affiliation": "University of Toronto Mississauga, Canada"},
    {"name": "Sharon Oviatt", "affiliation": "Monash University, Australia"},
    {"name": "Marilyn Lennon", "affiliation": "University of Strathclyde, UK"},
    {"name": "Martin Halvey", "affiliation": "University of Strathclyde, UK"},
    {"name": "Lynne Hall", "affiliation": "University of Sunderland, UK"},
    {"name": "Jennefer Hart", "affiliation": "BBC, UK"},
    {"name": "Cayley MacArthur", "affiliation": "University of Waterloo, Canada"},
    {"name": "Cale Passmore", "affiliation": "University of Saskatchewan, Canada"},
    {"name": "Sunyoung Kim", "affiliation": "Rutgers University, US"},
    {"name": "Edith Law", "affiliation": "University of Waterloo, Canada"},
    {"name": "Louise Barkhuus", "affiliation": "IT University of Copenhagen, Denmark"},
    {"name": "David Flatla", "affiliation": "University of Guelph, Canada"},
    {"name": "Anicia Peters", "affiliation": "Namibia University of Science and Technology, Namibia"},
    {"name": "Anke Brock", "affiliation": "Ecole Nationale de l’Aviation Civie, France"},
    {"name": "Nitesh Goyal", "affiliation": "Google, US"},
    {"name": "Gopinaath Kannabiran", "affiliation": "Aarhus University, Denmark"},
    {"name": "Sue Fussell", "affiliation": "Cornell University, US"},
    {"name": "Hao-Chuan Wang", "affiliation": "University of California Davis, US"},
    {"name": "Naomi Yamashita", "affiliation": "Nippon Telegraph and Telephone Corporation, Japan"},
    {"name": "Daria Loi", "affiliation": "Intel Labs, US"},
    {"name": "Jofish Kaye", "affiliation": "Mozilla, US"},
    {"name": "Oliver Bates", "affiliation": "Lancaster University, UK"},
    {"name": "Adrian Friday", "affiliation": "Lancaster University, UK"},
    {"name": "Mike Hazas", "affiliation": "Lancaster University, UK"},
    {"name": "Christian Remy", "affiliation": "Aarhus University, Denmark"},
    {"name": "Maria Wolters", "affiliation": "University of Edinburgh, UK"},
    {"name": "Dakuo Wang", "affiliation": "IBM Research, US"},
    {"name": "Fatma Meawad", "affiliation": "University of Glasgow, Singapore"},
    {"name": "Rina R. Wehbe", "affiliation": "University of Waterloo, Canada"},
    {"name": "Cristina Zaga", "affiliation": "University of Twente, The Netherlands"},
    {"name": "Carman Neustaedter", "affiliation": "Simon Fraser University, Canada"},
    {"name": "Tony Tang", "affiliation": "University of Calgary, Canada"},
    {"name": "William (Bill) Hamilton", "affiliation": "New Mexico State University, US"},
    {"name": "Euan Freeman", "affiliation": "University of Glasgow, UK"},
    {"name": "Irina Shklovski", "affiliation": "IT University of Copenhagen, Denmark"},
    {"name": "Mark Handel", "affiliation": "Facebook, US"},
    {"name": "Elizabeth Churchill", "affiliation": "Google, US"},
    {"name": "Matt Jones", "affiliation": "Swansea University, UK"},
    {"name": "David McGookin", "affiliation": "Aalto University, Finland"},
    {"name": "Joanna Bergström-Lehtovirta", "affiliation": "University of Copenhagen, Denmark"},
    {"name": "Anusha Withana", "affiliation": "Saarland University, Germany"},
    {"name": "Elizabeth Buie", "affiliation": "Northumbria University, UK"},
    {"name": "Lisa Tweedie", "affiliation": "TIBCO, UK"},
    {"name": "Alan Dix", "affiliation": "Swansea University, UK"},
    {"name": "David Lindlbauer", "affiliation": "ETH Zurich, Switzerland"},
    {"name": "Roman Rädle", "affiliation": "Aarhus University, Denmark"},
    {"name": "Carol Klyver", "affiliation": "Foundations of Excellence"},
    {"name": "Roxane Rose", "affiliation": "Executivevents"},
    {"name": "Taylor Vick", "affiliation": "Executivevents"}
]


CHI_committee = [
  {"name": "Lynne Baillie", "affiliation": "Heriot Watt University"},
  {"name": "Florian Alt", "affiliation": "Bundeswehr University Munich"},
  {"name": "Keith Vertanen", "affiliation": "Michigan Technological University"},
  {"name": "Magy Seif El-Nasr", "affiliation": "Northeastern University"},
  {"name": "Teresa Hirzle", "affiliation": "Ulm University"},
  {"name": "Theodoros Georgiou", "affiliation": "Heriot-Watt University"},
  {"name": "Erica Kleinman", "affiliation": "University of California Santa Cruz"},
  {"name": "Alexander Meschtscherjakov", "affiliation": "University of Salzburg"},
  {"name": "Andreas Riener", "affiliation": "TH Ingolstadt"},
  {"name": "Aneesha Singh", "affiliation": "University College London"},
  {"name": "Anirudha Joshi", "affiliation": "IIT Bombay"},
  {"name": "Ahmed Sabbir Arif", "affiliation": "University of California, Merced"},
  {"name": "Bastian Pfleging", "affiliation": "Eindhoven University of Technology"},
  {"name": "Benjamin Tag", "affiliation": "University of Melbourne"},
  {"name": "Blase Ur", "affiliation": "University of Chicago"},
  {"name": "Briane Paul Samson", "affiliation": "Future University Hakodate & De La Salle University"},
  {"name": "Benjamin Hanrahan", "affiliation": "Pennsylvania State University"},
  {"name": "Clara Caldeira", "affiliation": "UC Irvine"},
  {"name": "Claudio Pinhanez", "affiliation": "IBM Research"},
  {"name": "Daniel Buschek", "affiliation": "University of Bayreuth, Germany"},
  {"name": "Daniel Rough", "affiliation": "University College Dublin"},
  {"name": "Rahul Divekar", "affiliation": "RPI"},
  {"name": "Tanja Döring", "affiliation": "University of Bremen"},
  {"name": "Eduardo Velloso", "affiliation": "University of Melbourne"},
  {"name": "Elin Carstensdottir", "affiliation": "University of California at Santa Cruz"},
  {"name": "Elisa Mekeler", "affiliation": "Aalto University"},
  {"name": "Enrico Rukzio", "affiliation": "University of Ulm"},
  {"name": "Elizabeth Veinott", "affiliation": "Michigan Technological University"},
  {"name": "Frank Bentley", "affiliation": "Yahoo"},
  {"name": "Giovanni Troiano", "affiliation": "Northeastern University"},
  {"name": "Hans-Christian Jetter", "affiliation": "University of Applied Sciences Upper Austria, Hagenberg Campus"},
  {"name": "Henning Pohl", "affiliation": "University of Copenhagen"},
  {"name": "Tobias Höllerer", "affiliation": "University of California Santa Barbara"},
  {"name": "Jin Huang", "affiliation": "A M As Institute of Software, Chinese Academy of Sciences (ISCAS)"},
  {"name": "Jamie Mahoney", "affiliation": "Northumbria University"},
  {"name": "Jan Gugenheimer", "affiliation": "Institut Polytechnique de Paris"},
  {"name": "Jasmin Niess", "affiliation": "University of Bremen"},
  {"name": "Ken Pfeuffer", "affiliation": "Bundeswehr University Munich"},
  {"name": "Edward Lank", "affiliation": "University of Waterloo"},
  {"name": "Effie Law", "affiliation": "Leicester University"},
  {"name": "Markus Funk", "affiliation": "Cerence Inc."},
  {"name": "Mark Billinghurst", "affiliation": "University of South Australia"},
  {"name": "Mark Dunlop", "affiliation": "University of Strathclyde"},
  {"name": "Mathew Aylett", "affiliation": "CEREProc"},
  {"name": "Erin Cherry", "affiliation": "Northrop Grumman Mission Systems"},
  {"name": "Mirjana Prpa", "affiliation": "SIAT SFU"},
  {"name": "Andres Lucero", "affiliation": "Aalto University"},
  {"name": "Pawel Wozniak", "affiliation": "Utrecht University"},
  {"name": "Peter Frohlich", "affiliation": "AIT"},
  {"name": "Qian Yang", "affiliation": "Carnegie Mellon University"},
  {"name": "Ronald Schroeter", "affiliation": "Queensland University of Technology"},
  {"name": "Stephen Intille", "affiliation": "Northeastern University"},
  {"name": "Salvatore Andolina", "affiliation": "University of Palermo"},
  {"name": "Sayan Sarcar", "affiliation": "University of Tsukuba"},
  {"name": "Stefan Schneegass", "affiliation": "University of Duisburg-Essen"},
  {"name": "Stephen Uzor", "affiliation": "Cambridge University"},
  {"name": "Sean Rintel", "affiliation": "Microsoft Research"},
  {"name": "Thomas Kosch", "affiliation": "TU Darmstadt"},
  {"name": "Tilman Dingler", "affiliation": "University of Melbourne"},
  {"name": "Joe Tulio", "affiliation": "Google"},
  {"name": "Uwe Grünefeld", "affiliation": "University of Duisburg-Essen"},
  {"name": "Ville Mäkelä", "affiliation": "LMU Munich"},
  {"name": "Brian Bailey", "affiliation": "University of Illinois"},
  {"name": "Nicola Dell", "affiliation": "Cornell University"},
  {"name": "Rama Adithya Varanasi", "affiliation": "Cornell University"},
  {"name": "Afsaneh Doryab", "affiliation": "University of Virginia"},
  {"name": "Aditya Vashistha", "affiliation": "Cornell"},
  {"name": "Adrian Clear", "affiliation": "Northumbria University"},
  {"name": "Ali Agha Raza", "affiliation": "LUMS Pakistan"},
  {"name": "André Calero Valdez", "affiliation": "RWTH Aachen University"},
  {"name": "Bran Knowles", "affiliation": "Lancaster University"},
  {"name": "Robert Xiao", "affiliation": "University of British Columbia"},
  {"name": "Carrie Demmans Epp", "affiliation": "University of Alberta"},
  {"name": "Kurt Luther", "affiliation": "Virginia Tech"},
  {"name": "Margot Brereton", "affiliation": "Queensland University of Technology"},
  {"name": "Mary Lou Maher", "affiliation": "UNC Charlotte"},
  {"name": "Maletsabisa (Tsabi) Molapo", "affiliation": "IBM Research Africa"},
  {"name": "Maggie Jack", "affiliation": "Cornell / UC Irvine"},
  {"name": "Maria Menendez Blanco", "affiliation": "The Free University of Bozen-Bolzano"},
  {"name": "Matthew Mauriello", "affiliation": "Stanford"},
  {"name": "Andrii Matviienko", "affiliation": "Technical University Darmstadt"},
  {"name": "Priyank Chandra", "affiliation": "University of Toronto"},
  {"name": "Ranjitha Kumar", "affiliation": "University of Illinois"},
  {"name": "Rita Orji", "affiliation": "Dalhousie University"},
  {"name": "Scarlett Miller", "affiliation": "Penn State"},
  {"name": "Sunyoung Kim", "affiliation": "Rutgers University"},
  {"name": "Shamsi Iqbal", "affiliation": "MSR"},
  {"name": "Sowmya Somanath", "affiliation": "University of Victoria"},
  {"name": "Vineet Pandey", "affiliation": "Harvard"},
  {"name": "Betsy DiSalvo", "affiliation": "Georgia Tech"},
  {"name": "Erin Walker", "affiliation": "University of Pittsburgh"},
  {"name": "Ishrat Ahmed", "affiliation": "University of Pittsburgh"},
  {"name": "Ahmed Kharrufa", "affiliation": "Newcastle University"},
  {"name": "Alexis Hinker", "affiliation": "University of Washington"},
  {"name": "Alice Oh", "affiliation": "KAIST - School of Computing"},
  {"name": "Anthony Pellicone", "affiliation": "University of Maryland, College Park"},
  {"name": "Briana Morrison", "affiliation": "University of Nebraska Omaha"},
  {"name": "Chris Frauenberger", "affiliation": "Aarhus University"},
  {"name": "Carolyn Rose", "affiliation": "Carnegie Mellon University"},
  {"name": "Edith Law", "affiliation": "University of Waterloo"},
  {"name": "Elena Glassman", "affiliation": "Harvard University"},
  {"name": "Elisa Rubegni", "affiliation": "Lancaster University"},
  {"name": "Eleanor O'Rourke", "affiliation": "Northwestern University"},
  {"name": "Florian Block", "affiliation": "University of York"},
  {"name": "Gahgene Gweon", "affiliation": "Seoul National University"},
  {"name": "Colin Gray", "affiliation": "Purdue"},
  {"name": "Gabreila Richard", "affiliation": "Pennsylvania State University"},
  {"name": "Erik Harpstead", "affiliation": "Carnegie Mellon University"},
  {"name": "Iulian Radu", "affiliation": "Harvard University"},
  {"name": "Derek Lomas", "affiliation": "Delft"},
  {"name": "Jason Yip", "affiliation": "University of Washington"},
  {"name": "Jessica Roberts", "affiliation": "Georgia Tech"},
  {"name": "Juho Kim", "affiliation": "KAIST"},
  {"name": "Kayla Desportes", "affiliation": "New York University"},
  {"name": "Katie Davis", "affiliation": "University of Washington"},
  {"name": "Kristy Boyer", "affiliation": "University of Florida"},
  {"name": "Rene Kizilcec", "affiliation": "Cornell University"},
  {"name": "Lana Yarosh", "affiliation": "University of Minnesota"},
  {"name": "Lisa Anthony", "affiliation": "University of Florida"},
  {"name": "Matthew Easterday", "affiliation": "Northwestern University"},
  {"name": "Min Chi", "affiliation": "North Carolina State"},
  {"name": "Mike Horn", "affiliation": "Northwestern"},
  {"name": "Michelle Lui", "affiliation": "University of Toronto"},
  {"name": "Michael Lee", "affiliation": "New Jersey Institute of Technology"},
  {"name": "Monica Landoni", "affiliation": "Università Della Svizzera Italiana"},
  {"name": "Oren Zuckerman", "affiliation": "Interdisciplinary Center Herzliya"},
  {"name": "Petr Slovak", "affiliation": "University College London"},
  {"name": "Zach Pardos", "affiliation": "Berkeley"},
  {"name": "Paul Denny", "affiliation": "University of Auckland, New Zealand"},
  {"name": "Phillip Guo", "affiliation": "UC San Diego"},
  {"name": "Rebecca Quintana", "affiliation": "University of Michigan"},
  {"name": "Ricarose Roque", "affiliation": "University of Colorado"},
  {"name": "Robb Lindgren", "affiliation": "University of Illinois"},
  {"name": "Roberto Martinez-Maldonado", "affiliation": "Monash University"},
  {"name": "Sayamindu Dasgupta", "affiliation": "UNC Chapel Hill"},
  {"name": "Selen Turkay", "affiliation": "Queensland University of Technology"},
  {"name": "Tawfiq Ammari", "affiliation": "University of Michigan"},
  {"name": "Tammy Clegg", "affiliation": "University of Maryland, College Park"},
  {"name": "Uta Hinrichs", "affiliation": "University of Saint Andrews"},
  {"name": "Viktoria Pammer-Schindler", "affiliation": "Graz University of Technology"},
  {"name": "Xu Wang", "affiliation": "Carnegie Mellon University"},
  {"name": "Munmun Chaudhury", "affiliation": "Georgia Tech"},
  {"name": "Thomas Ludwig", "affiliation": "University of Siegen"},
  {"name": "Max Krüger", "affiliation": "University of Siegen"},
  {"name": "Alexander Boden", "affiliation": "Fraunhofer FIT"},
  {"name": "Casey Dugan", "affiliation": "IBM"},
  {"name": "Clemens Nylandsted Klokmose", "affiliation": "Aarhus University"},
  {"name": "Elizabeth Murnane", "affiliation": "Dartmouth College"},
  {"name": "Fabiano Pinatti", "affiliation": "University of Siegen"},
{ "name": "Haiyi Zhu", "affiliation": "Carnegie Mellon University" },
  { "name": "Ingmar Weber", "affiliation": "Qatar Computing Research Institute" },
  { "name": "Jed Brubaker", "affiliation": "CU Boulder" },
  { "name": "Jacob Thebault-Spieker", "affiliation": "Virginia Tech" },
  { "name": "Jalal Mahmud", "affiliation": "IBM Research" },
  { "name": "Matthieu Tixier", "affiliation": "University of Troyes" },
  { "name": "Mike Clarke", "affiliation": "Facebook" },
  { "name": "Michael Prilla", "affiliation": "TU Clausthal" },
  { "name": "Mor Naaman", "affiliation": "Cornell Tech" },
  { "name": "Nicholas Diakopoulos", "affiliation": "Northwestern University" },
  { "name": "Niels van Berkel", "affiliation": "Aalborg University" },
  { "name": "Robert Soden", "affiliation": "University of Colorado" },
  { "name": "Stevie Chancellor", "affiliation": "Northwestern University" },
  { "name": "Tawfiq Ammari", "affiliation": "University of Michigan" },
  { "name": "Thomas Olsson", "affiliation": "Tampere University" },
  { "name": "Liam D. Turner", "affiliation": "Cardiff University" },
  { "name": "Vivek Singh", "affiliation": "Rutgers University" },
  { "name": "Yelena Mejova", "affiliation": "ISI Foundation" },
  { "name": "Kathrin Gerling", "affiliation": "KU Leuven" },
  { "name": "Pejman Mirza-Babaei", "affiliation": "Ontario Tech University" },
  { "name": "Maria Aufheimer", "affiliation": "KU Leuven" },
  { "name": "Z Toups", "affiliation": "New Mexico State University" },
  { "name": "Richard Wetzel", "affiliation": "Hochschule Luzern" },
  { "name": "Jinghui Cheng", "affiliation": "Polytechnique Montréal" },
  { "name": "Perttu Hamalainen", "affiliation": "Aalto University" },
  { "name": "Casper Harteveld", "affiliation": "Northeastern University" },
  { "name": "Günter Wallner", "affiliation": "TU Eindhoven" },
  { "name": "Loutfouz Zaman", "affiliation": "Ontario Tech University" },
  { "name": "Simone Kriglstein", "affiliation": "University of Vienna" },
  { "name": "Nicholas Graham", "affiliation": "Queen's University" },
  { "name": "April Tyack", "affiliation": "Aalto University" },
  { "name": "Alena Denisova", "affiliation": "City University London" },
  { "name": "Jim Wallace", "affiliation": "University of Waterloo" },
  { "name": "Jessica Hammer", "affiliation": "Carnegie Mellon University" },
  { "name": "Elizabeth Bonsignore", "affiliation": "University of Maryland" },
  { "name": "Katja Rogers", "affiliation": "University of Waterloo" },
  { "name": "Annika Waern", "affiliation": "Uppsala University" },
  { "name": "Penny Kyburz", "affiliation": "Australian National University" },
  { "name": "Melissa Rogerson", "affiliation": "University of Melbourne" },
  { "name": "Oğuz 'Oz' Buruk", "affiliation": "Tampere University" },
  { "name": "Madison Klarkowski", "affiliation": "University of Saskatchewan" },
  { "name": "Apu Kapadia", "affiliation": "Indiana University" },
  { "name": "Emilee Rader", "affiliation": "Michigan State University" },
  { "name": "Megan Knittel", "affiliation": "Michigan State University" },
  { "name": "Yasemin Acar", "affiliation": "Leibniz University Hannover" },
  { "name": "Alexander De Luca", "affiliation": "Google Inc." },
  { "name": "Chris Kanich", "affiliation": "University of Illinois, Chicago" },
  { "name": "Eran Toch", "affiliation": "Tel Aviv University" },
  { "name": "Florian Schaub", "affiliation": "University of Michigan, Ann Arbor" },
  { "name": "Gunnar Stevens", "affiliation": "University of Siegen" },
  { "name": "Janne Lindqvist", "affiliation": "Aalto, Rutgers" },
  { "name": "Jose Such", "affiliation": "King's College London" },
  { "name": "Katharina Krombholz", "affiliation": "CISPA Helmholtz Center for Information Security (Saarbrücken, Germany)" },
  { "name": "Lujo Bauer", "affiliation": "Carnegie Mellon University" },
  { "name": "Lynne Coventry", "affiliation": "Northumbria University" },
  { "name": "Mainack Mondal", "affiliation": "IIT Kharagpur" },
  { "name": "Manya Sleeper", "affiliation": "Google Inc." },
  { "name": "Marc Langheinrich", "affiliation": "University of Lugano, Università della Svizzera italiana (USI)" },
  { "name": "Marshini Chetty", "affiliation": "University of Chicago" },
  { "name": "Mohamed Khamis", "affiliation": "University of Glasgow" },
  { "name": "Alena Naiakshina", "affiliation": "Rheinische Friedrich-Wilhelms-Universität Bonn" },
  { "name": "Nora McDonald", "affiliation": "UMBC" },
  { "name": "Kent Seamons", "affiliation": "Brigham Young University" },
  { "name": "Shion Guha", "affiliation": "Marquette University" },
  { "name": "Tousif Ahmed", "affiliation": "Samsung Research" },
  { "name": "Yaxing Yao", "affiliation": "Carnegie Mellon University" },
  { "name": "Yang Wang", "affiliation": "University of Illinois at Urbana-Champaign" },
  { "name": "Zinaida Benenson", "affiliation": "University of Erlangen-Nuremberg" },
  { "name": "Niklas Elmqvist", "affiliation": "University of Maryland" },
  { "name": "Bongshin Lee", "affiliation": "Microsoft" },
  { "name": "Tongshuang (Sherry) Wu", "affiliation": "University of Washington" },
  { "name": "Alvitta Ottley", "affiliation": "Washington University of St. Louis" },
  { "name": "Anastasia Bezerianos", "affiliation": "University of Paris-Saclay" },
  { "name": "Bum Chul Kwon", "affiliation": "IBM Research" },
  { "name": "Danielle Albers Szafir", "affiliation": "University of Colorado Boulder" },
  { "name": "Eytan Adar", "affiliation": "University of Michigan" },
  { "name": "Kim Marriott", "affiliation": "Monash University" },
  { "name": "Kwan-Liu Ma", "affiliation": "University of California, Davis" },
  { "name": "Leilani Battle", "affiliation": "University of Maryland, College Park" },
  { "name": "Lyn Bartram", "affiliation": "Simon Fraser University" },
  { "name": "Matthew Kay", "affiliation": "Northwestern University" },
  { "name": "Melanie Tory", "affiliation": "Tableau Software" },
  { "name": "Miguel Nacenta", "affiliation": "University of Victoria" },
  { "name": "Rita Borgo", "affiliation": "King's College London" },
  { "name": "Ron Metoyer", "affiliation": "University of Notre Dame" },
  { "name": "Shixia Liu", "affiliation": "Tsinghua University" },
  { "name": "Tamara Munzner", "affiliation": "University of British Columbia" },
  { "name": "Vidya Setlur", "affiliation": "Tableau Research" },
  { "name": "Nadia Boukhelifa", "affiliation": "INRAE" },
  { "name": "Raimund Dachselt", "affiliation": "Technische Universität Dresden" },
  { "name": "Jinwook Seo", "affiliation": "Seoul National University" },
  { "name": "Jo Vermeulen", "affiliation": "Autodesk Research" },
  { "name": "Khairi Reda", "affiliation": "Indiana University-Purdue University Indianapolis" },
  { "name": "Xiaoru Yuan", "affiliation": "Peking University" },
  { "name": "Adam Perer", "affiliation": "Carnegie Mellon University" },
  { "name": "Xianghua Ding", "affiliation": "Fudan University" },
  { "name": "Gavin Doherty", "affiliation": "Trinity College Dublin" },
  { "name": "Kevin Doherty", "affiliation": "Technical University of Denmark" },
  { "name": "Eun Kyoung Choe", "affiliation": "University of Maryland" },
  { "name": "Marilyn Lennon", "affiliation": "University of Strathclyde" },
  { "name": "Yixuan (Janice) Zhang", "affiliation": "Georgia Institute of Technology" },
  { "name": "Xinning Gui", "affiliation": "Penn State University" },
  { "name": "Amanda Lazar", "affiliation": "University of Maryland, College Park" },
  { "name": "David Coyle", "affiliation": "University College Dublin" },
  { "name": "Aisling O’Kane", "affiliation": "University of Bristol" },
  { "name": "Sun Young Park", "affiliation": "University of Michigan" },
  { "name": "Francisco Nunes", "affiliation": "Fraunhofer Portugal AICOS" },
  { "name": "Ignacio Avellino", "affiliation": "University of Maryland Baltimore County" },
  { "name": "Swamy Ananthanarayan", "affiliation": "Monash University, Melbourne" },
  { "name": "Eric Hekler", "affiliation": "UC San Diego" },
  { "name": "Lauren Wilcox", "affiliation": "GeogiaTech/Google" },
  { "name": "Mohit Jain", "affiliation": "Microsoft Research India" },
  { "name": "Ryan M. Kelly", "affiliation": "University of Melbourne" },
  { "name": "Nervo Verdezoto", "affiliation": "Cardiff University" },
  { "name": "Stephanie Wilson", "affiliation": "City University, London" },
  { "name": "Daniel Epstein", "affiliation": "University of California, Irvine" },
  { "name": "Pin Sym Foong", "affiliation": "National University of Singapore" },
  { "name": "Xiaojuan Ma", "affiliation": "Hong Kong University of Science and Technology" },
  { "name": "Greg Wadley", "affiliation": "University of Melbourne" },
  { "name": "Stephen Schueller", "affiliation": "University of California Irvine" },
  { "name": "Hao-Hua Chu", "affiliation": "National Taiwan University" },
  { "name": "Christina Chung", "affiliation": "Indiana University" },
  { "name": "Mayank Goel", "affiliation": "Carnegie Mellon University" },
  { "name": "Kellie Morrissey", "affiliation": "University of Limerick" },
  { "name": "Pedja Klasnja", "affiliation": "University of Michigan" },
  { "name": "Elizabeth Eikey", "affiliation": "UC San Diego" },
  { "name": "Roisin McNaney", "affiliation": "Monash University" },
  { "name": "Sonali Mishra", "affiliation": "University of Washington" },
  { "name": "Troels Mønsted", "affiliation": "Roskilde University, Roskilde, Denmark" },
  { "name": "Lisa Vizer", "affiliation": "University of North Carolina at Chapel Hill" },
  { "name": "Susanne Boll", "affiliation": "University of Oldenburg" },
  { "name": "Cosmin Munteanu", "affiliation": "University of Toronto" },
  { "name": "Christina Schneegass", "affiliation": "Ludwig-Maximilians-Universität München" },
  { "name": "Aisling Kelliher", "affiliation": "Virginia Tech" },
{ "name": "Amy Hurst", "affiliation": "NYU" },
  { "name": "Aqueasha Martin-Hammond", "affiliation": "Indiana University - Purdue University Indianapolis" },
  { "name": "Benjamin Gorman", "affiliation": "Bournemouth University" },
  { "name": "Carolyn Pang", "affiliation": "McGill University" },
  { "name": "Dafne Zuleima Morgado Ramirez", "affiliation": "University College London" },
  { "name": "Danielle Bragg", "affiliation": "Microsoft Research" },
  { "name": "Dragan Ahmetovic", "affiliation": "University of Milan" },
  { "name": "Fabio Paterno", "affiliation": "CNR Italy" },
  { "name": "Foad Hamidi", "affiliation": "U of Maryland" },
  { "name": "Frank Steinicke", "affiliation": "University of Hamburg" },
  { "name": "Helen Petrie", "affiliation": "University of York" },
  { "name": "Jenny Waycott", "affiliation": "U of Melbourne" },
  { "name": "João Guerreiro", "affiliation": "Universidade de Lisboa" },
  { "name": "Josep Blat", "affiliation": "Universitat Pompeu Fabra" },
  { "name": "Kathleen McCoy", "affiliation": "University of Delaware" },
  { "name": "Kyle Rector", "affiliation": "U of Iowa" },
  { "name": "Martez Mott", "affiliation": "Microsoft Research" },
  { "name": "Michael Crabb", "affiliation": "Univ of Dundee" },
  { "name": "Mingming Fan", "affiliation": "Rochester Institute of Technology" },
  { "name": "Robin Brewer", "affiliation": "U of Michigan" },
  { "name": "Shaomei Wu", "affiliation": "Facebook" },
  { "name": "Shaun Kane", "affiliation": "University of Colorado Boulder" },
  { "name": "Stacy Branham", "affiliation": "U of California" },
  { "name": "Sunyoung Kim", "affiliation": "Rutgers" },
  { "name": "Timothy Neate", "affiliation": "King's College London" },
  { "name": "Uran Oh", "affiliation": "Ewha Woman's University" },
  { "name": "Wilko Heuten", "affiliation": "OFFIS Institute for IT" },
  { "name": "Yasamin Heshmat", "affiliation": "Simon Fraser University" },
  { "name": "Kristina Andersen", "affiliation": "TU Eindhoven" },
  { "name": "Christopher Le Dantec", "affiliation": "Georgia Tech" },
  { "name": "Alyssa Rumsey", "affiliation": "Georgia Tech" },
  { "name": "Jeffrey Bardzell", "affiliation": "Pennsylvania State University" },
  { "name": "Marianna Obrist", "affiliation": "University College London" },
  { "name": "Fernando Maestre", "affiliation": "Indiana University" },
  { "name": "James Pierce", "affiliation": "University of Washington" },
  { "name": "Will Odom", "affiliation": "SFU" },
  { "name": "Tom Jenkins", "affiliation": "ITU" },
  { "name": "Marti Louw", "affiliation": "CMU" },
  { "name": "Steven Dow", "affiliation": "UCSD" },
  { "name": "Christina Harrington", "affiliation": "DePaul" },
  { "name": "Michael Nitsche", "affiliation": "GaTech" },
  { "name": "Jonas Fritsch", "affiliation": "ITU" },
  { "name": "Peter Krogh", "affiliation": "Aarhus University" },
  { "name": "Stacey Kuznetsov", "affiliation": "Arizona" },
  { "name": "Maliheh Ghajargar", "affiliation": "Malmo" },
  { "name": "Colin Gray", "affiliation": "Purdue" },
  { "name": "Patrizia Marti", "affiliation": "University of Siena" },
  { "name": "Pedro Sanches", "affiliation": "KTH" },
  { "name": "Rachel Clarke", "affiliation": "Northumbria University" },
  { "name": "Marie Louise Juul Søndergaard", "affiliation": "KTH" },
  { "name": "Chris Elsden", "affiliation": "University of Edinburgh" },
  { "name": "David Chatting", "affiliation": "Goldsmiths" },
  { "name": "Vasiliki Tsaknaki", "affiliation": "IT University of Copenhagen (ITU)" },
  { "name": "Daisy Yoo", "affiliation": "TU Eindhoven" },
  { "name": "Yaliang Chuang", "affiliation": "TU Eindhoven" },
  { "name": "Emeline Brulé", "affiliation": "Sussex University" },
  { "name": "Karin Slegers", "affiliation": "Tilburg University" },
  { "name": "Corina Sas", "affiliation": "Lancaster University" },
  { "name": "Rohit Ashok Khot", "affiliation": "RMIT University" },
  { "name": "Bruna Petreca", "affiliation": "RCA" },
  { "name": "Parinya Punpongsanon", "affiliation": "Osaka University" },
  { "name": "Shaun Lawson", "affiliation": "Northumbria University" },
  { "name": "Paul Strohmeier", "affiliation": "Saarland University" },
  { "name": "Ana Tajadura-Jiménez", "affiliation": "Universidad Carlos III de Madrid" },
  { "name": "Verena Fuchsberger", "affiliation": "University of Salzburg" },
  { "name": "Michael Lankes", "affiliation": "FH Hagenberg" },
  { "name": "Laura Maye", "affiliation": "University College Cork" },
  { "name": "Marion Koelle", "affiliation": "Saarland University" },
  { "name": "Oliver Schneider", "affiliation": "University of Waterloo" },
  { "name": "Szu-Yu (Cyn) Liu", "affiliation": "Indiana University" },
  { "name": "Heekyoung Jung", "affiliation": "University of Cincinnati" },
  { "name": "Netta Iivari", "affiliation": "Oulu University" },
  { "name": "Troy Nachtigal", "affiliation": "HvA, Amsterdam" },
  { "name": "Johanna Ylipulli", "affiliation": "Aalto University" },
  { "name": "Vasilis Vlachokyriakos", "affiliation": "University of Newcastle" },
  { "name": "Eunice Sari", "affiliation": "UX Indonesia" },
  { "name": "Sebastian Boring", "affiliation": "Aalborg University Copenhagen" },
  { "name": "Christian Holz", "affiliation": "ETH Zurich" },
  { "name": "Alyssa Rumsey", "affiliation": "Georgia Tech" },
  { "name": "Jeffrey Bardzell", "affiliation": "Pennsylvania State University" },
  { "name": "Marianna Obrist", "affiliation": "University College London" },
  { "name": "Fernando Maestre", "affiliation": "Indiana University" },
  { "name": "Mike Chen", "affiliation": "National Taiwan University" },
  { "name": "Anne Roudaut", "affiliation": "University of Bristol" },
  { "name": "Sean Follmer", "affiliation": "Stanford University" },
  { "name": "Ollie Hanton", "affiliation": "University of Bristol" },
  { "name": "Aakar Gupta", "affiliation": "Facebook" },
  { "name": "Alanson Sample", "affiliation": "University of Michigan" },
  { "name": "Alex Mariakakis", "affiliation": "University of Washington" },
  { "name": "Alexandra Ion", "affiliation": "ETH Zürich" },
  { "name": "Aluna Everitt", "affiliation": "University of Bristol" },
  { "name": "Andrea Bianchi", "affiliation": "KAIST" },
  { "name": "Andreas Fender", "affiliation": "University of Sussex" },
  { "name": "Andy Wilson", "affiliation": "Microsoft Research" },
  { "name": "Céline Coutrix", "affiliation": "CNRS Grenoble" },
  { "name": "Christine Dierk", "affiliation": "UC Berkeley" },
  { "name": "David Holman", "affiliation": "Tactual Labs" },
  { "name": "David Lindlbauer", "affiliation": "ETH Zürich" },
  { "name": "Diego Martinez Plasencia", "affiliation": "University of Sussex" },
  { "name": "Eric Whitmire", "affiliation": "Facebook Reality Labs" },
  { "name": "Erin Solovey", "affiliation": "Worcester Polytechnic Institute" },
  { "name": "Eve Hoggan", "affiliation": "Aarhus University" },
  { "name": "Eyal Ofek", "affiliation": "Microsoft Research" },
  { "name": "Florian Echtler", "affiliation": "Bauhaus-Universität Weimar" },
  { "name": "Fraser Anderson", "affiliation": "Autodesk Research" },
  { "name": "Hans Gellersen", "affiliation": "Aarhus University" },
  { "name": "Hasti Seifi", "affiliation": "Max Planck Institute" },
  { "name": "Hyunyoung Kim", "affiliation": "University of Copenhagen" },
  { "name": "Jan Borchers", "affiliation": "RWTH Aachen" },
  { "name": "Jason Alexander", "affiliation": "University of Bath" },
  { "name": "Jennifer Pearson", "affiliation": "Swansea University" },
  { "name": "Jürgen Steimle", "affiliation": "Saarland University" },
  { "name": "Kashyap Todi", "affiliation": "Aalto University" },
  { "name": "Laura Trutoiu", "affiliation": "Magic Leap" },
  { "name": "Lining Yao A F Am", "affiliation": "Carnegie Mellon University" },
  { "name": "Liwei Chen", "affiliation": "NCTU Taiwan" },
  { "name": "Lung-Pan Cheng", "affiliation": "National Taiwan University" },
  { "name": "Marcos Serrano", "affiliation": "University of Toulouse" },
  { "name": "Marynel Vázquez", "affiliation": "Yale University" },
  { "name": "Michael Haller", "affiliation": "University of Applied Sciences Upper Austria" },
  { "name": "Mike Fraser", "affiliation": "University of Bath" },
  { "name": "Misha Sra", "affiliation": "UC Santa Barbara" },
  { "name": "Oussama Metatla", "affiliation": "University of Bristol" },
  { "name": "Peggy Chi", "affiliation": "Google" },
  { "name": "Raf Ramakers", "affiliation": "Hasselt University" },
  { "name": "Ruta Desai", "affiliation": "Facebook" },
  { "name": "Sara Nabil", "affiliation": "Queen's University" },
  { "name": "Shengdong Zhao", "affiliation": "National University of Singapore" },
  { "name": "Simon Robinson", "affiliation": "Swansea University" },
  { "name": "Simon Voelker", "affiliation": "RWTH Aachen University" },
  { "name": "Steve Feiner", "affiliation": "Columbia University" },
  { "name": "Steven Houben", "affiliation": "Lancaster University" },
  { "name": "Takuji Narumi", "affiliation": "University of Tokyo" },
  { "name": "Thomas Pietrzak", "affiliation": "University of Lille" },
  { "name": "Tovi Grossman", "affiliation": "University of Toronto" },
  { "name": "Valkyrie Savage", "affiliation": "Tactual Labs" },
  { "name": "Xiaojun Bi", "affiliation": "Stony Brook University" },
  { "name": "Yuhang Zhao", "affiliation": "Cornell Tech" },
{"name": "Gary Hsieh", "affiliation": "University of Washington"},
  {"name": "Maria Wolters", "affiliation": "University of Edinburgh"},
  {"name": "Duncan Reid", "affiliation": "University of Edinburgh"},
  {"name": "Peter Tolmie", "affiliation": "University of Siegen"},
  {"name": "Naomi Yamashita", "affiliation": "NTT"},
  {"name": "Chi-Lan Yang", "affiliation": "University of Tokyo"},
  {"name": "Neha Kumar", "affiliation": "Georgia Tech"},
  {"name": "Max Wilson", "affiliation": "University of Nottingham"},
  {"name": "Naveena Karusala", "affiliation": "University of Washington"},
  {"name": "Alexandra Papoutsaki", "affiliation": "Pomona College, USA"},
  {"name": "Aske Mottelson", "affiliation": "University of Copenhagen, Denmark"},
  {"name": "Stanley Chang", "affiliation": "National Chiao Tung University, Taiwan"},
  {"name": "Cristian Bogdan", "affiliation": "KTH, Sweden"},
  {"name": "Dave Murray-Rust", "affiliation": "University of Edinburgh, USA"},
  {"name": "Yvette Wohn", "affiliation": "New Jersey Institute of Technology, USA"},
  {"name": "Guihuan Feng", "affiliation": "Nanjing University, China"},
  {"name": "Jamy Li", "affiliation": "University of Twente, Netherlands"},
  {"name": "Janet Huang", "affiliation": "Technical University of Eindhoven, Netherlands"},
  {"name": "Joel Chan", "affiliation": "University of Maryland, USA"},
  {"name": "Lionel Robert", "affiliation": "University of Michigan, USA"},
  {"name": "Martin Flintham", "affiliation": "Nottingham University, UK"},
  {"name": "Sven Mayer", "affiliation": "Carnegie Mellon University, USA"},
  {"name": "Mia Suh", "affiliation": "Google, USA"},
  {"name": "Mihaela Vorvoreanu", "affiliation": "Microsoft, USA"},
  {"name": "Nikolas Martelaro", "affiliation": "Carnegie Mellon University, USA"},
  {"name": "Paul Parsons", "affiliation": "Purdue University, USA"},
  {"name": "Patrick Shih", "affiliation": "Indiana University, USA"},
  {"name": "Sucheta Ghoshal", "affiliation": "Georgia Tech, USA"},
  {"name": "Tonja Machulla", "affiliation": "Ludwig Maximilian University Munich, Germany"},
  {"name": "Annika Hupfeld", "affiliation": "Eindhoven University of Technology, Netherlands"},
  {"name": "Claudia-Lavinia Ignat", "affiliation": "LORIA-Inria, France"},
  {"name": "Dakuo Wang", "affiliation": "IBM Research, USA"},
  {"name": "Ewa Luger", "affiliation": "University of Edinburgh, UK"},
  {"name": "Ge Gao", "affiliation": "University of Maryland, USA"},
  {"name": "Hwajung Hong", "affiliation": "Seoul National University, Korea"},
  {"name": "Jina Huh-Yoo", "affiliation": "Drexel University, USA"},
  {"name": "Joel Fischer", "affiliation": "University of Nottingham, UK"},
  {"name": "John Tang", "affiliation": "Microsoft Research, USA"},
  {"name": "Lizzie Coles-Kemp", "affiliation": "Royal Holloway University London, UK"},
  {"name": "Mark Rouncefield", "affiliation": "Lancaster University, UK"},
  {"name": "Maria Roussou", "affiliation": "National and Kapodistrian University of Athens, Greece"},
  {"name": "Hideyuki Nakanishi", "affiliation": "Osaka University, Japan"},
  {"name": "Patricia Cornelio Martinez", "affiliation": "University College London, UK"},
  {"name": "Daisuke Sakamoto", "affiliation": "Hokkaido University, Japan"},
  {"name": "Sanorita Dey", "affiliation": "University of Maryland, USA"},
  {"name": "Simon Perrault", "affiliation": "Singapore University of Technology and Design, Singapore"},
  {"name": "Yasuyuki Sumi", "affiliation": "Future University Hakodate, Japan"},
  {"name": "Tesh Goyal", "affiliation": "Google, USA"},
  {"name": "Tommaso Colombino", "affiliation": "Naver Labs, France"},
  {"name": "Tone Bratteteig", "affiliation": "Unknown"},
  {"name": "Uichin Lee", "affiliation": "Korea Advanced Institute of Science and Technology, Korea"},
  {"name": "Vanessa Evers", "affiliation": "Nanyang Technological University, Singapore"},
  {"name": "Yubo Kou", "affiliation": "Pennsylvania State University, USA"},
  {"name": "Yun Huang", "affiliation": "University of Illinois at Urbana-Champaign, USA"},
  {"name": "Ben Cowan", "affiliation": "University College Dublin, Ireland"},
  {"name": "Boriana Koleva", "affiliation": "University of Nottingham, UK"},
  {"name": "Can Liu", "affiliation": "City University of Hong Kong, Hong Kong"},
  {"name": "Carla Griggio", "affiliation": "Aarhus University, Denmark"},
  {"name": "Lewis Chuang", "affiliation": "Ludwig-Maximilian-Universität München, Germany"},
  {"name": "Elena Agapie", "affiliation": "UC Irvine, USA"},
  {"name": "Eva Hornecker", "affiliation": "Bauhaus-Universität Weimar, Germany"},
  {"name": "Heloisa Candello", "affiliation": "IBM Research, Brazil"},
  {"name": "Horia Maior", "affiliation": "University of Lincoln, UK"},
  {"name": "John Rooksby", "affiliation": "Northumbria University, UK"},
  {"name": "Luigi De Russis", "affiliation": "Politecnico di Torino, Italy"},
  {"name": "Max Birk", "affiliation": "TU Eindhoven University of Technology, Netherlands"},
  {"name": "Ming Yin", "affiliation": "Purdue University, USA"},
  {"name": "Michael Madaio", "affiliation": "Microsoft Research, USA"},
  {"name": "Bonnie Nardi", "affiliation": "UC Irvine, USA"},
  {"name": "Nithya Sambasivan", "affiliation": "Google AI, USA"},
  {"name": "Paula Lago", "affiliation": "Kyushu Institute of Technology, Japan"},
  {"name": "Phil Palanque", "affiliation": "Université Paul Sabatier – Toulouse 3, France"},
  {"name": "Pernilla Qvarfordt", "affiliation": "eBay, USA"},
  {"name": "Sauvik Das", "affiliation": "Georgia Tech, USA"},
  {"name": "Susan Fussell", "affiliation": "Cornell University, USA"},
  {"name": "Shagun Jhaver", "affiliation": "University of Washington, USA"},
  {"name": "Ding Wang", "affiliation": "Microsoft Research, India"},
  {"name": "Loren Terveen", "affiliation": "University of Minnesota, USA"},
  {"name": "Kentaro Toyama", "affiliation": "University of Michigan, USA"},
  {"name": "Shumin Zhai", "affiliation": "Google, USA"},
  {"name": "Jakita O. Thomas", "affiliation": "Auburn University, USA"},
  {"name": "Caroline Appert", "affiliation": "CNRS, Université Paris Saclay"},
  {"name": "Carl Gutwin", "affiliation": "University of Saskatchewan"},
  {"name": "Eugénie Brasier", "affiliation": "CNRS & Université Paris Saclay"},
  {"name": "Alix Goguey", "affiliation": "Université Grenoble-Alpes"},
  {"name": "Amy Zhang", "affiliation": "University of Washington"},
  {"name": "Barrett Ens", "affiliation": "Monash University"},
  {"name": "Bjoern Hartmann", "affiliation": "University of California Berkeley"},
  {"name": "Andrea Bunt", "affiliation": "University of Manitoba"},
  {"name": "Charles Perin", "affiliation": "University of Victoria"},
  {"name": "Lap-Fai (Craig)", "affiliation": "George Mason University"},
  {"name": "Daniel Leithinger", "affiliation": "University of Colorado"},
  {"name": "Emmanuel Pietriga", "affiliation": "Inria"},
  {"name": "Elena L. Glassman", "affiliation": "Harvard"},
  {"name": "Huaishu Peng", "affiliation": "University of Maryland"},
  {"name": "Jeffrey Bigham", "affiliation": "Carnegie Mellon University"},
  {"name": "Jessica Cauchard", "affiliation": "Ben Gurion University of the Negev"},
  {"name": "Jeff Nichols", "affiliation": "Apple"},
  {"name": "Julian Frommel", "affiliation": "University of Saskatchewan"},
  {"name": "Jun Kato", "affiliation": "National Institute of Advanced Industrial Science and Technology (AIST)"},
  {"name": "Michelle Annett", "affiliation": "MishMashMakers"},
  {"name": "Rong-Hao Liang", "affiliation": "Eindhoven University of Technology"},
  {"name": "Radu-Daniel Vatavu", "affiliation": "University Stefan cel Mare of Suceava, Romania"},
  {"name": "Ruofei Du", "affiliation": "Google"},
  {"name": "Scott Bateman", "affiliation": "University of New Brunswick"},
  {"name": "Stéphane Huot", "affiliation": "Inria"},
  {"name": "Sylvain Malacria", "affiliation": "Inria"},
  {"name": "Valentina Shin", "affiliation": "Adobe Research"},
  {"name": "Joel Lanir", "affiliation": "University of Haifa"},
  {"name": "Shaowen Bardzell", "affiliation": "Pennsylvania State University"},
  {"name": "Rob Comber", "affiliation": "Royal Institute of Technology Stockholm"},
  {"name": "Patrycja Zdziarska", "affiliation": "Indiana University (USA)"},
{"name": "Amanda Menking", "affiliation": "U of Toronto"},
  {"name": "Angelika Strohmayer", "affiliation": "Northumbria University"},
  {"name": "Bryan Semaan", "affiliation": "Syracuse U"},
  {"name": "Chiara Rossitto", "affiliation": "Stockholm University"},
  {"name": "Clara Crivellaro", "affiliation": "Newcastle"},
  {"name": "Deborah Tatar", "affiliation": "Virginia Tech"},
  {"name": "Eli Blevis", "affiliation": "Indiana University"},
  {"name": "Gopianath Kanabiran", "affiliation": "Aarhus Univ"},
  {"name": "Syed Ishtiaque Ahmed", "affiliation": "U of Toronto"},
  {"name": "Jennifer Rode", "affiliation": "UCL"},
  {"name": "John Vines", "affiliation": "Northumbria University"},
  {"name": "Katta Spiel", "affiliation": "KU Leuven || Universität Wien"},
  {"name": "Lone Hansen", "affiliation": "Aarhus Univ"},
  {"name": "Silvia Lindtner", "affiliation": "U of Michigan"},
  {"name": "Lilly Irani", "affiliation": "UCSD"},
  {"name": "Lynn Dombrowski", "affiliation": "IUPUI"},
  {"name": "Mark Blythe", "affiliation": "Northumbria University"},
  {"name": "Maurizio Teli", "affiliation": "Aalborg Univ"},
  {"name": "Melissa Densmore", "affiliation": "University of Cape Town"},
  {"name": "Michael Mueller", "affiliation": "IBM"},
  {"name": "Niloufar Salehi", "affiliation": "Berkeley"},
  {"name": "Reem Talhouk", "affiliation": "Newcastle"},
  {"name": "Sarah Fox", "affiliation": "CMU"},
  {"name": "Steve Jackson", "affiliation": "Cornell"},
  {"name": "Steve Harrison", "affiliation": "Virginia Tech"},
  {"name": "Teresa Almeida", "affiliation": "ITU"},
  {"name": "Tessy Cerrantto Pargman", "affiliation": "Stockholm University"},
  {"name": "Austin Toombs", "affiliation": "Purdue"},
  {"name": "Victor Kaptelinin", "affiliation": "Umea University"},
  {"name": "Volker Wulf", "affiliation": "U of Siegen"},
  {"name": "Rebecca Fiebrink", "affiliation": "Creative Computing Institute, University of the Arts London"},
  {"name": "Per Ola Kristensson", "affiliation": "University of Cambridge"},
  {"name": "Esben Sørig", "affiliation": "Goldsmiths University of London"},
  {"name": "Andrew Howes", "affiliation": "University of Birmingham"},
  {"name": "Azza Abouzied", "affiliation": "NYU Abu Dhabi"},
  {"name": "Abby Liu", "affiliation": "IRCAM"},
  {"name": "Yea-Seul Kim", "affiliation": "University of Wisconsin-Madison"},
  {"name": "Antti Oulasvirta", "affiliation": "Aalto University"},
  {"name": "Amy Pavel", "affiliation": "Carnegie Mellon, Apple"},
  {"name": "Brian Lim", "affiliation": "National University of Singapore"},
  {"name": "Byungjoo Lee", "affiliation": "KAIST"},
  {"name": "Gonzalo Ramos", "affiliation": "Microsoft Research"},
  {"name": "John Dudley", "affiliation": "University of Cambridge"},
  {"name": "John Williamson", "affiliation": "University of Glasgow"},
  {"name": "John Zimmerman", "affiliation": "Carnegie Mellon"},
  {"name": "Krzysztof Gajos", "affiliation": "Harvard University"},
  {"name": "Samantha Krening", "affiliation": "Ohio State University"},
  {"name": "Marco Gillies", "affiliation": "Goldsmiths University of London"},
  {"name": "Mike Schaekermann", "affiliation": "Amazon AI"},
  {"name": "Nikola Banovic", "affiliation": "Michigan"},
  {"name": "Otmar Hilliges", "affiliation": "ETH Zurich"},
  {"name": "Mark Riedl", "affiliation": "Georgia Tech"},
  {"name": "Roderick Murray-Smith", "affiliation": "University of Glasgow"},
  {"name": "Simone Stumpf", "affiliation": "City University of London"},
  {"name": "Vera Liao", "affiliation": "IBM"},
  {"name": "Xiang ‘Anthony’ Chen", "affiliation": "UCLA"}
]





from difflib import SequenceMatcher

def similar(a, b):
    return SequenceMatcher(None, a, b).ratio()

def disambiguate_authors(chairs_list, previous_list):
    disambiguated_list = []
    used_names = set()

    for chair in chairs_list:
        best_match = None
        max_similarity = 0

        for prev_chair in previous_list:
            similarity = similar(chair['name'], prev_chair['name'])
            # print(chair['name'])
            if similarity > max_similarity and chair['affiliation'] == prev_chair['affiliation']:
                max_similarity = similarity
                best_match = prev_chair

        if best_match is not None and best_match['name'] not in used_names:
            disambiguated_list.append(best_match)
            used_names.add(best_match['name'])
        else:
            disambiguated_list.append(chair)

    return disambiguated_list

# Combine all the committee chairs lists
all_chairs = committee_data_1 + committee_data + chairs_2 + chairs_2020 + chairs_2019 + CHI_committee


# Disambiguate and remove duplicates
unique_chairs = disambiguate_authors(all_chairs, all_chairs)

print(unique_chairs)

import csv

# Specify the filename for the CSV file
csv_filename = 'CHI_PC.csv'

# Define the field names for the CSV header
field_names = ['name', 'affiliation']

# Write the data to the CSV file
with open(csv_filename, 'w', newline='', encoding='utf-8') as csvfile:
    writer = csv.DictWriter(csvfile, fieldnames=field_names)

    # Write the header
    writer.writeheader()

    # Write the committee_chairs data
    writer.writerows(unique_chairs)

print(f"The data has been written to {csv_filename}")


