siggraph_data = [
    {"name": "Erik Brunvand", "affiliation": "SIGGRAPH 2023 Conference Chair"},
    {"name": "Yoon Chung Han", "affiliation": "SIGGRAPH 2023 Art Gallery Chair"},
    {"name": "Nicolas Henchoz", "affiliation": "SIGGRAPH 2023 Art Papers Chair"},
    {"name": "Chris Wyman", "affiliation": "SIGGRAPH 2023 Courses Chair"},
    {"name": "Eveline Falcão", "affiliation": "SIGGRAPH 2023 Creative Development Director"},
    {"name": "Nick Jushchyshyn", "affiliation": "SIGGRAPH 2023 Education Chair"},
    {"name": "Kalina Borkiewicz", "affiliation": "SIGGRAPH 2023 Electronic Theater Director"},
    {"name": "Mashhuda Glencross", "affiliation": "SIGGRAPH 2023 Emerging Technologies Chair"},
    {"name": "Ginger Alford", "affiliation": "SIGGRAPH 2023 Frontiers Chair"},
    {"name": "Josef Spjut", "affiliation": "SIGGRAPH 2023 Games Focus Area Chair"},
    {"name": "Susan Reiser", "affiliation": "SIGGRAPH 2023 General Submissions Chair"},
    {"name": "Joseph Cychosz", "affiliation": "SIGGRAPH 2023 GraphicsNet Chair"},
    {"name": "Bonnie Mitchell", "affiliation": "SIGGRAPH 2023 History Chair"},
    {"name": "Anna Carolina Muller Queiroz", "affiliation": "SIGGRAPH 2023 Immersive Pavilion Chair"},
    {"name": "Asiya Gizatulina", "affiliation": "SIGGRAPH 2023 International Resources Committee Chair"},
    {"name": "Courtney Starrett", "affiliation": "SIGGRAPH 2023 Labs Chair"},
    {"name": "James Tompkin", "affiliation": "SIGGRAPH 2023 Posters Chair"},
    {"name": "Christine Holmes", "affiliation": "SIGGRAPH 2023 Production Sessions Chair"},
    {"name": "Cem Yuksel", "affiliation": "SIGGRAPH 2023 Real-Time Live! Chair"},
    {"name": "Meaghan Long", "affiliation": "SIGGRAPH 2023 Student Volunteer Chair"},
    {"name": "Alla Sheffer", "affiliation": "SIGGRAPH 2023 Technical Papers Chair"},
    {"name": "Julia Read", "affiliation": "SIGGRAPH 2023 VR Theater Director"},
    {"name": "Andres Burbano", "affiliation": "SIGGRAPH 2024 Conference Chair"}
]

siggraph_2022_data = [
    {"name": "Munkhtsetseg Nandigjav", "affiliation": "SIGGRAPH 2022 Conference Chair (she/her)"},
    {"name": "Daria Tsoupikova", "affiliation": "SIGGRAPH 2022 Art Gallery Chair (she/her)"},
    {"name": "Daniel Cardoso Llach", "affiliation": "SIGGRAPH 2022 Art Papers Chair (he/him)"},
    {"name": "Courtney Starrett", "affiliation": "SIGGRAPH 2022 Community Engagement Chair (she/her)"},
    {"name": "Tamar Shinar", "affiliation": "SIGGRAPH 2022 Courses Chair"},
    {"name": "Eveline Falcão", "affiliation": "SIGGRAPH 2022 Creative Development Director (she/her)"},
    {"name": "Monica Cappiello", "affiliation": "SIGGRAPH 2022 Education Liaison (she/her)"},
    {"name": "Darin Kyoichi Grant", "affiliation": "SIGGRAPH 2022 Electronic Theater Director (he/him)"},
    {"name": "MK Haley", "affiliation": "SIGGRAPH 2022 Emerging Technologies Chair"},
    {"name": "Vathsal Veena Shashidhar", "affiliation": "SIGGRAPH 2022 Frontiers Chair (he/him)"},
    {"name": "Elizabeth Baumel", "affiliation": "SIGGRAPH 2022 Games Focus Area Chair (they/them)"},
    {"name": "Chris Redmann", "affiliation": "SIGGRAPH 2022 General Submissions Chair (he/him)"},
    {"name": "Stanley Chan", "affiliation": "SIGGRAPH 2022 GraphicsNet Chair (he/him)"},
    {"name": "Derek Ham", "affiliation": "SIGGRAPH 2022 Immersive Pavilion Chair (he/him)"},
    {"name": "June Kim", "affiliation": "SIGGRAPH 2022 International Resources Committee Chair (she/her)"},
    {"name": "Kristy Pron", "affiliation": "SIGGRAPH 2022 Labs Chair"},
    {"name": "Olga Diamanti", "affiliation": "SIGGRAPH 2022 Posters Chair (she/her)"},
    {"name": "Stephanie Eisenberg", "affiliation": "SIGGRAPH 2022 Production Sessions Chair (she/her)"},
    {"name": "Yibing Jiang", "affiliation": "SIGGRAPH 2022 Real-Time Live! Chair (she/her)"},
    {"name": "Ben Lok", "affiliation": "SIGGRAPH 2022 Retrospective Chair"},
    {"name": "Roy C. Anthony", "affiliation": "SIGGRAPH 2022 Special Projects Chair"},
    {"name": "Diana Arellano", "affiliation": "SIGGRAPH 2022 Student Volunteers Chair (she/her)"},
    {"name": "Niloy J. Mitra", "affiliation": "SIGGRAPH 2022 Technical Papers Chair (he/him)"},
    {"name": "Yangos Hadjiyannis", "affiliation": "SIGGRAPH 2022 VR Theater Director (he/him)"},
    {"name": "Erik Brunvand", "affiliation": "SIGGRAPH 2023 Conference Chair"},
]

siggraph_2021_data = [
    {"name": "Jeremias Pol Jeremias-Vila", "affiliation": "SIGGRAPH 2021 Conference Chair"},
    {"name": "Tomasz Bednarz", "affiliation": "ACM SIGGRAPH Frontiers Chair"},
    {"name": "Angus Forbes", "affiliation": "SIGGRAPH 2021 Art Gallery Chair"},
    {"name": "Daria Tsoupikova", "affiliation": "SIGGRAPH 2021 Art Papers Chair"},
    {"name": "Ana Cecilia Balliache", "affiliation": "SIGGRAPH 2021 Attendee Experience Manager"},
    {"name": "Fernando de Goes", "affiliation": "SIGGRAPH 2021 Courses Chair"},
    {"name": "Vib Soundrarajah", "affiliation": "SIGGRAPH 2021 Creative Development Director"},
    {"name": "Monica Cappiello", "affiliation": "SIGGRAPH 2021 Education Liaison"},
    {"name": "Mark Elendt", "affiliation": "SIGGRAPH 2021 Electronic Theater Director"},
    {"name": "Paul Dietz", "affiliation": "SIGGRAPH 2021 Emerging Technologies Chair"},
    {"name": "Carlos Gonzalez-Ochoa", "affiliation": "SIGGRAPH 2021 Games Focus Area Chair"},
    {"name": "Chris Redmann", "affiliation": "SIGGRAPH 2021 General Submissions Chair"},
    {"name": "Callie Holderman", "affiliation": "SIGGRAPH 2021 Immersive Pavilion Chair"},
    {"name": "June Kim", "affiliation": "SIGGRAPH 2021 International Resources Chair"},
    {"name": "Michael Reed", "affiliation": "SIGGRAPH 2021 Labs Chair"},
    {"name": "David Spoelstra", "affiliation": "SIGGRAPH 2021 Platform Technology Liaison"},
    {"name": "Melina Skouras", "affiliation": "SIGGRAPH 2021 Posters Chair"},
    {"name": "John Kalaigian", "affiliation": "SIGGRAPH 2021 Production Sessions Chair"},
    {"name": "Chris Evans", "affiliation": "SIGGRAPH 2021 Real-Time Live! Chair"},
    {"name": "Andres Burbano", "affiliation": "SIGGRAPH 2021 Retrospective Chair"},
    {"name": "Ian Failes", "affiliation": "SIGGRAPH 2021 Special Projects Chair"},
    {"name": "Alex Bryant", "affiliation": "SIGGRAPH 2021 Student Volunteers Chair"},
    {"name": "Sylvain Paris", "affiliation": "SIGGRAPH 2021 Technical Papers Chair"},
    {"name": "Larry Bafia", "affiliation": "SIGGRAPH 2021 VR Theater Director"},
    {"name": "Muunuu Nandigjav", "affiliation": None},
]

siggraph_2020_data = [
    {"name": "Kristy Pron", "affiliation": "Walt Disney Imagineering (SIGGRAPH 2020 Conference Chair)"},
    {"name": "MK Haley", "affiliation": "Walt Disney Imagineering (ACM SIGGRAPH Frontiers Chair)"},
    {"name": "Christine Holmes", "affiliation": "Blue Sky Studios (Adaptability Focus Area Co-Chair)"},
    {"name": "Natalie Rountree", "affiliation": "Not specified (Adaptability Focus Area Co-Chair)"},
    {"name": "Nik Apostolides", "affiliation": "Johns Hopkins University (Art Gallery Chair)"},
    {"name": "Andres Burbano", "affiliation": "Universidad de los Andes (Art Papers Chair)"},
    {"name": "Corinne Price", "affiliation": "ICF (Attendee Experience Manager)"},
    {"name": "Susan Reiser", "affiliation": "UNC Asheville & Vassar College (Courses Chair)"},
    {"name": "Larry Bafia", "affiliation": "Centre for Digital Media (Creative Development Director)"},
    {"name": "Munkhtsetseg Nandigjav", "affiliation": "Savannah College of Art and Design (Electronic Theater Director)"},
    {"name": "Andrew Duchowski", "affiliation": "Clemson University (Education Liaison)"},
    {"name": "Dani Belko", "affiliation": "Facebook (Emerging Technologies Chair)"},
    {"name": "Carlos Gonzalez-Ochoa", "affiliation": "Not specified (Games Focus Area Chair)"},
    {"name": "Ginger Alford", "affiliation": "SMU Lyle School of Engineering (General Submissions Chair)"},
    {"name": "David Spoelstra", "affiliation": "MediaMachine LLC (GraphicsNet Chair)"},
    {"name": "Chris Redmann", "affiliation": "Unity Technologies (Immersive Pavilion Chair)"},
    {"name": "June Kim", "affiliation": "University of New South Wales (International Resources Chair)"},
    {"name": "Ana Cecilia Balliache Liendo", "affiliation": "Schell Games (Posters Chair)"},
    {"name": "Derrick Nau", "affiliation": "DreamWorks Animation (Production Sessions Chair)"},
    {"name": "Marc Olano", "affiliation": "University of Maryland, Baltimore County (Real-Time Live! Chair)"},
    {"name": "Thierry Frey", "affiliation": "Reel FX Animation Studios (SIGGRAPH Executive Experience Co-Chair)"},
    {"name": "Joanne Green", "affiliation": "University of Pittsburgh (SIGGRAPH Executive Experience Co-Chair)"},
    {"name": "Erik Brunvand", "affiliation": "University of Utah (SIGGRAPH Labs Co-Chair)"},
    {"name": "Forrest Lucas", "affiliation": "Two Bit Circus (SIGGRAPH Labs Co-Chair)"},
    {"name": "Sarah Rust", "affiliation": "Rooster Teeth (Student Volunteers Chair)"},
    {"name": "Szymon Rusinkiewicz", "affiliation": "Princeton University (Technical Papers Chair)"},
    {"name": "Monica Cappiello", "affiliation": "Cogswell Polytechnical College (VR Theater Director)"},
    {"name": "Pol Jeremias-Vila", "affiliation": "Pixar Animation Studios (SIGGRAPH 2021 Conference Chair)"},
]


siggraph_2019_data = [
    {"name": "Mikki Rose", "affiliation": "Blue Sky Studios (SIGGRAPH 2019 Conference Chair)"},
    {"name": "Natalie Rountree", "affiliation": "Not specified (Adaptive Technology Co-Chair)"},
    {"name": "Dylan Moore", "affiliation": "Not specified (Adaptive Technology Co-Chair)"},
    {"name": "Brittany Ransom", "affiliation": "California State University Long Beach (Art Gallery Chair)"},
    {"name": "Everardo Reyes", "affiliation": "Université Paris 8 (Art Papers Editor)"},
    {"name": "Joshua Grow", "affiliation": "Zorroa (Attendee Experience Manager)"},
    {"name": "Mark Elendt", "affiliation": "SideFX Software (Birds of a Feather Coordinator)"},
    {"name": "Adele Newton", "affiliation": "Executive Director, CS-Can (Business Symposium Chair)"},
    {"name": "Emily Hsu", "affiliation": "Blizzard Entertainment (Computer Animation Festival Director)"},
    {"name": "Michael Reed", "affiliation": "Blue Sky Studios (Courses Chair)"},
    {"name": "Munkhtsetseg Nandigjav", "affiliation": "Savannah College of Art and Design (Creative Development Director)"},
    {"name": "Andrew Duchowski", "affiliation": "Clemson University (Education Liaison)"},
    {"name": "Courtney Starrett", "affiliation": "Seton Hall University (Emerging Technologies Chair)"},
    {"name": "Christine Holmes", "affiliation": "Blue Sky Studios (Experience Hall Manager)"},
    {"name": "Christopher Evans", "affiliation": "Epic Games (Games Co-Chair)"},
    {"name": "Laurent Delayen", "affiliation": "Epic Games (Games Co-Chair)"},
    {"name": "Ginger Alford", "affiliation": "Trinity Valley School & Southern Methodist University (General Submissions Chair)"},
    {"name": "Carlos Cardenas", "affiliation": "Qualcomm Inc. (GraphicsNet Chair)"},
    {"name": "June Kim", "affiliation": "University of New South Wales (International Resources Chair)"},
    {"name": "Jim Kilmer", "affiliation": "The OPAL Group (Pathfinders Coordinator)"},
    {"name": "AJ Christensen", "affiliation": "National Center for Supercomputing Applications (NCSA) (Posters Coordinator)"},
    {"name": "Derrick Nau", "affiliation": "DreamWorks Animation (Production Sessions Chair)"},
    {"name": "Gracie Arenas Stritmatter", "affiliation": "BioWare/EA (Real-Time Live! Chair)"},
    {"name": "MK Haley", "affiliation": "Walt Disney Imagineering (SIGGRAPH Frontiers Talks Chair)"},
    {"name": "Corinne Price", "affiliation": "ICF (Student Volunteer Chair)"},
    {"name": "Chrissy Cain", "affiliation": "Santa Cruz Bicycles (Studio Chair)"},
    {"name": "Olga Sorkine-Hornung", "affiliation": "ETH Zurich (Technical Papers Chair)"},
    {"name": "Maxwell Planck", "affiliation": "Adventure Lab (VR Theater Director)"},
    {"name": "Victoria Rege", "affiliation": "Graphcore (Immersive Pavilion Chair)"},
    {"name": "Kristy Pron", "affiliation": "Walt Disney Imagineering (SIGGRAPH 2020 Conference Chair)"},
]


