OSDI_2023=[
    {"name": "Roxana Geambasu", "affiliation": "Columbia University"},
    {"name": "Ed Nightingale", "affiliation": "Apple"},
    {"name": "Atul Adya", "affiliation": "Databricks"},
    {"name": "Rachit Agarwal", "affiliation": "Cornell University"},
    {"name": "Nitin Agrawal", "affiliation": "Google"},
    {"name": "Ramnatthan Alagappan", "affiliation": "University of Illinois at Urbana–Champaign"},
    {"name": "Jeremy Andrus", "affiliation": "Apple"},
    {"name": "Sebastian Angel", "affiliation": "University of Pennsylvania"},
    {"name": "Mahesh Balakrishnan", "affiliation": "Confluent"},
    {"name": "Adam Belay", "affiliation": "MIT CSAIL"},
    {"name": "Emery Berger", "affiliation": "University of Massachusetts Amherst"},
    {"name": "Edouard Bugnion", "affiliation": "EPFL"},
    {"name": "George Candea", "affiliation": "EPFL"},
    {"name": "Kang Chen", "affiliation": "Tsinghua University"},
    {"name": "Vijay Chidambaram", "affiliation": "The University of Texas at Austin and VMware Research"},
    {"name": "Mosharaf Chowdhury", "affiliation": "University of Michigan"},
    {"name": "Byung-Gon Chun", "affiliation": "Seoul National University and FriendliAI"},
    {"name": "Asaf Cidon", "affiliation": "Columbia University"},
    {"name": "Manuel Costa", "affiliation": "Microsoft Research"},
    {"name": "Landon Cox", "affiliation": "Microsoft Research"},
    {"name": "Natacha Crooks", "affiliation": "University of California, Berkeley"},
    {"name": "Jon Crowcroft", "affiliation": "University of Cambridge"},
    {"name": "Heming Cui", "affiliation": "University of Hong Kong"},
    {"name": "Dilma Da Silva", "affiliation": "Texas A&M University"},
    {"name": "Murat Demirbas", "affiliation": "Amazon Web Services"},
    {"name": "Ittay Eyal", "affiliation": "Technion—Israel Institute of Technology"},
    {"name": "Jason Flinn", "affiliation": "Meta"},
    {"name": "Bryan Ford", "affiliation": "EPFL"},
    {"name": "Aishwarya Ganesan", "affiliation": "University of Illinois at Urbana-Champaign and VMware Research"},
    {"name": "Phillip Gibbons", "affiliation": "Carnegie Mellon University"},
    {"name": "Yossi Gilad", "affiliation": "Hebrew University of Jerusalem"},
    {"name": "Joseph Gonzalez", "affiliation": "University of California, Berkeley"},
    {"name": "Andreas Haeberlen", "affiliation": "University of Pennsylvania and Roblox"},
    {"name": "Steven Hand", "affiliation": "Google"},
    {"name": "Tim Harris", "affiliation": "Microsoft"},
    {"name": "Wenjun Hu", "affiliation": "Yale University"},
    {"name": "Ryan Huang", "affiliation": "Johns Hopkins University"},
    {"name": "Rüdiger Kapitza", "affiliation": "Friedrich-Alexander-Universität Erlangen-Nürnberg"},
    {"name": "Brad Karp", "affiliation": "University College London"},
    {"name": "Baris Kasikci", "affiliation": "University of Michigan"},
    {"name": "Eddie Kohler", "affiliation": "Harvard University"},
    {"name": "Mathias Lécuyer", "affiliation": "University of British Columbia"},
    {"name": "Philip Levis", "affiliation": "Google and Stanford University"},
    {"name": "Amit Levy", "affiliation": "Princeton University"},
    {"name": "Jinyang Li", "affiliation": "New York University"},
    {"name": "Hyeontaek Lim", "affiliation": "Google"},
    {"name": "Wyatt Lloyd", "affiliation": "Princeton University"},
    {"name": "Jay Lorch", "affiliation": "Microsoft Research"},
    {"name": "Shan Lu", "affiliation": "University of Chicago"},
    {"name": "Martin Maas", "affiliation": "Google"},
    {"name": "Jonathan Mace", "affiliation": "Max Planck Institute for Software Systems (MPI-SWS)"},
    {"name": "Ratul Mahajan", "affiliation": "University of Washington and Intentionet"},
    {"name": "Z. Morley Mao", "affiliation": "University of Michigan and Google"},
    {"name": "James Mickens", "affiliation": "Harvard University"},
    {"name": "Thomas Moscibroda", "affiliation": "Microsoft"},
    {"name": "Deepak Narayanan", "affiliation": "Microsoft Research"},
    {"name": "Ravi Netravali", "affiliation": "Princeton University"},
    {"name": "Jason Nieh", "affiliation": "Columbia University"},
    {"name": "Cristina Nita-Rotaru", "affiliation": "Northeastern University"},
    {"name": "Shadi Noghabi", "affiliation": "Microsoft Research"},
    {"name": "Aurojit Panda", "affiliation": "New York University"},
    {"name": "KyoungSoo Park", "affiliation": "Korea Advanced Institute of Science and Technology (KAIST)"},
    {"name": "Bryan Parno", "affiliation": "Carnegie Mellon University"},
    {"name": "Daniel Peek", "affiliation": "Meta"},
    {"name": "Peter Pietzuch", "affiliation": "Imperial College London"},
    {"name": "Dan Ports", "affiliation": "Microsoft Research"},
    {"name": "Costin Raiciu", "affiliation": "University Politehnica of Bucharest"},
    {"name": "David Richardson", "affiliation": "Apple"},
    {"name": "Luis Rodrigues", "affiliation": "INESC-ID and Instituto Superior Técnico, University of Lisbon"},
    {"name": "Christopher Rossbach", "affiliation": "The University of Texas at Austin and Katana Graph"},
    {"name": "Malte Schwarzkopf", "affiliation": "Brown University"},
    {"name": "Marco Serafini", "affiliation": "University of Massachusetts Amherst"},
    {"name": "Marc Shapiro", "affiliation": "Sorbonne-Université–LIP6 and Inria"},
    {"name": "Ji-Yong Shin", "affiliation": "Northeastern University"}
]