popl_2023 = [
    {"name": "Amal Ahmed", "affiliation": "Northeastern University, USA"},
    {"name": "Robert Bruce Findler", "affiliation": "Northwestern University, United States"},
    {"name": "Deepak Garg", "affiliation": "MPI-SWS, Germany"},
    {"name": "François Pottier", "affiliation": "Inria, France"},
    {"name": "Andreas Abel", "affiliation": "Gothenburg University, Sweden"},
    {"name": "Nada Amin", "affiliation": "Harvard University, United States"},
    {"name": "Stephanie Balzer", "affiliation": "Carnegie Mellon University, United States"},
    {"name": "Josh Berdine", "affiliation": "Meta, United Kingdom"},
    {"name": "Karthikeyan Bhargavan", "affiliation": "Inria, France"},
    {"name": "Giuseppe Castagna", "affiliation": "CNRS; Université de Paris, France"},
    {"name": "Tej Chajed", "affiliation": "VMware Research, United States"},
    {"name": "Arthur Charguéraud", "affiliation": "Inria; Université de Strasbourg; CNRS; ICube, France"},
    {"name": "Koen Claessen", "affiliation": "Chalmers University of Technology, Sweden"},
    {"name": "Loris D'Antoni", "affiliation": "University of Wisconsin-Madison, United States"},
    {"name": "Ugo Dal Lago", "affiliation": "University of Bologna; Inria, Italy"},
    {"name": "Mila Dalla Preda", "affiliation": "University of Verona, Italy"},
    {"name": "Ornela Dardha", "affiliation": "University of Glasgow, United Kingdom"},
    {"name": "Benjamin Delaware", "affiliation": "Purdue University, United States"},
    {"name": "Alastair F. Donaldson", "affiliation": "Imperial College London; Google, United Kingdom"},
    {"name": "Richard A. Eisenberg", "affiliation": "Jane Street, United States"},
    {"name": "Constantin Enea", "affiliation": "Ecole Polytechnique / LIX / CNRS, France"},
    {"name": "Michael Greenberg", "affiliation": "Stevens Institute of Technology, United States"},
    {"name": "Ichiro Hasuo", "affiliation": "National Institute of Informatics, Japan"},
    {"name": "Hugo Herbelin", "affiliation": "Inria"},
    {"name": "Zhenjiang Hu", "affiliation": "Peking University, China"},
    {"name": "Suresh Jagannathan", "affiliation": "Purdue University, United States"},
    {"name": "Alan Jeffrey", "affiliation": "Roblox, United States"},
    {"name": "Patricia Johann", "affiliation": "Appalachian State University"},
    {"name": "Jacques-Henri Jourdan", "affiliation": "CNR, LMF, France"},
    {"name": "Ralf Jung", "affiliation": "ETH Zürich, Switzerland"},
    {"name": "Ohad Kammar", "affiliation": "University of Edinburgh, United Kingdom"},
    {"name": "Joost-Pieter Katoen", "affiliation": "RWTH Aachen University, Germany"},
    {"name": "Ekaterina Komendantskaya", "affiliation": "Heriot-Watt University, UK"},
    {"name": "Laura Kovacs", "affiliation": "Vienna University of Technology (TU Wien), Austria"},
    {"name": "Robbert Krebbers", "affiliation": "Radboud University Nijmegen, Netherlands"},
    {"name": "Lindsey Kuper", "affiliation": "University of California at Santa Cruz"},
    {"name": "Akash Lal", "affiliation": "Microsoft Research, United States"},
    {"name": "Xavier Leroy", "affiliation": "Collège de France, France"},
    {"name": "Mohsen Lesani", "affiliation": "University of California at Riverside"},
    {"name": "Daniel R. Licata", "affiliation": "Wesleyan University, United States"},
    {"name": "Matteo Maffei", "affiliation": "TU Wien"},
    {"name": "Isabella Mastroeni", "affiliation": "University of Verona, Italy"},
    {"name": "Christoph Matheja", "affiliation": "DTU, Denmark"},
    {"name": "Umang Mathur", "affiliation": "National University of Singapore, Singapore"},
    {"name": "Todd Millstein", "affiliation": "University of California at Los Angeles, United States"},
    {"name": "Andrzej Murawski", "affiliation": "University of Oxford, United Kingdom"},
    {"name": "Santosh Nagarakatte", "affiliation": "Rutgers University, United States"},
    {"name": "Aleksandar Nanevski", "affiliation": "IMDEA Software Institute, Spain"},
    {"name": "David Naumann", "affiliation": "Stevens Institute of Technology, United States"},
    {"name": "Dominic Orchard", "affiliation": "University of Kent, UK, United Kingdom"},
    {"name": "Klaus Ostermann", "affiliation": "University of Tübingen"},
    {"name": "Oded Padon", "affiliation": "VMware Research, United States"},
    {"name": "Michele Pagani", "affiliation": "IRIF - Université de Paris Cité, France"},
    {"name": "Marco Patrignani", "affiliation": "University of Trento, Italy"},
    {"name": "David Pichardie", "affiliation": "Meta, France"},
    {"name": "Brigitte Pientka", "affiliation": "McGill University, Canada"},
    {"name": "Benjamin C. Pierce", "affiliation": "University of Pennsylvania, United States"},
    {"name": "Clément Pit-Claudel", "affiliation": "EPFL / AWS, United States"},
    {"name": "Andreas Podelski", "affiliation": "University of Freiburg, Germany"},
    {"name": "Nadia Polikarpova", "affiliation": "University of California at San Diego, United States"},
    {"name": "Damien Pous", "affiliation": "CNRS"},
    {"name": "Christopher Pulte", "affiliation": "University of Cambridge, United Kingdom"},
    {"name": "Corina S. Păsăreanu", "affiliation": "Carnegie Mellon University, United States"},
    {"name": "Azalea Raad", "affiliation": "Imperial College London, United Kingdom"},
    {"name": "Robert Rand", "affiliation": "University of Chicago, United States"},
    {"name": "Noam Rinetzky", "affiliation": "Tel Aviv University, Israel"},
    {"name": "Amr Sabry", "affiliation": "Indiana University, United States"},
    {"name": "Malavika Samak", "affiliation": "CSAIL, MIT, United States"},
    {"name": "Taro Sekiyama", "affiliation": "National Institute of Informatics, Japan"},
    {"name": "Jonathan Sterling", "affiliation": "Aarhus University, Denmark"},
    {"name": "Aaron Stump", "affiliation": "University of Iowa, United States"},
    {"name": "Eijiro Sumii", "affiliation": "Tohoku University, Japan"},
    {"name": "Nicolas Tabareau", "affiliation": "Inria, France"},
    {"name": "Éric Tanter", "affiliation": "University of Chile"},
    {"name": "Joseph Tassarotti", "affiliation": "NYU, United States"},
    {"name": "Sam Tobin-Hochstadt", "affiliation": "Indiana University"},
    {"name": "Andrew Tolmach", "affiliation": "Portland State University, United States"},
    {"name": "Marco Vassena", "affiliation": "Utrecht University, Netherlands"},
    {"name": "David Walker", "affiliation": "Princeton University, United States"},
    {"name": "Conrad Watt", "affiliation": "University of Cambridge, United Kingdom"},
    {"name": "Theo Winterhalter", "affiliation": "INRIA Saclay, France"},
    {"name": "Ningning Xie", "affiliation": "Google Brain / University of Toronto, United Kingdom"},
    {"name": "Francesco Zappa Nardelli", "affiliation": "Meta, France"},
    {"name": "Elena Zucca", "affiliation": "University of Genoa, Italy"},
{"name": "Andrew Myers", "affiliation": "Cornell University"},
    {"name": "Amal Ahmed", "affiliation": "Northeastern University, USA"},
    {"name": "Ilya Sergey", "affiliation": "National University of Singapore, Singapore"},
    {"name": "Kristopher Micinski", "affiliation": "Syracuse University, United States"},
    {"name": "William J. Bowman", "affiliation": "University of British Columbia, Canada"},
    {"name": "Anders Miltner", "affiliation": "Simon Fraser University, United States"},
    {"name": "Jeehoon Kang", "affiliation": "KAIST, South Korea"},
    {"name": "Danfeng Zhang", "affiliation": "Pennsylvania State University, United States"},
    {"name": "Leonidas Lampropoulos", "affiliation": "University of Maryland, College Park, Greece"},
    {"name": "Mukund Raghothaman", "affiliation": "University of Southern California"},
    {"name": "Kostas Ferles", "affiliation": "Veridise Inc., United States"},
    {"name": "Yuepeng Wang", "affiliation": "Simon Fraser University, Canada"},
    {"name": "Shraddha Barke", "affiliation": "University of California at San Diego, United States"},
    {"name": "Konstantinos Kallas", "affiliation": "University of Pennsylvania, United States"},
    {"name": "Benjamin Delaware", "affiliation": "Purdue University, United States"},
    {"name": "Guilherme Espada", "affiliation": "University of Lisbon, Portugal"},
    {"name": "Nate Foster", "affiliation": "Cornell University, United States"},
    {"name": "Apoorv Ingle", "affiliation": "University of Iowa, United States"},
    {"name": "Neringa Young", "affiliation": "Lithuania"}
]

popl_2022 = [
    {"name": "Hongseok Yang", "affiliation": "KAIST, South Korea"},
    {"name": "Michael D. Adams", "affiliation": "University of Michigan, United States"},
    {"name": "Amal Ahmed", "affiliation": "Northeastern University, USA"},
    {"name": "Robert Atkey", "affiliation": "University of Strathclyde"},
    {"name": "Sandrine Blazy", "affiliation": "Univ Rennes, IRISA, France"},
    {"name": "David Broman", "affiliation": "KTH, Sweden"},
    {"name": "Michael Carbin", "affiliation": "Massachusetts Institute of Technology, United States"},
    {"name": "Alvin Cheung", "affiliation": "University of California, Berkeley"},
    {"name": "Wei-Ngan Chin", "affiliation": "National University of Singapore"},
    {"name": "Pierre Clairambault", "affiliation": "CNRS & ENS Lyon, France"},
    {"name": "Christos Dimoulas", "affiliation": "PLT @ Northwestern University, United States"},
    {"name": "Michael Emmi", "affiliation": "Amazon Web Services, United States"},
    {"name": "Ronald Garcia", "affiliation": "University of British Columbia"},
    {"name": "Radu Grigore", "affiliation": "Facebook, United Kingdom"},
    {"name": "Ronghui Gu", "affiliation": "Columbia University, United States"},
    {"name": "Matthew Hague", "affiliation": "Royal Holloway University of London, United Kingdom"},
    {"name": "Kihong Heo", "affiliation": "KAIST, South Korea"},
    {"name": "Ralf Hinze", "affiliation": "Technische Universität Kaiserslautern"},
    {"name": "Jan Hoffmann", "affiliation": "Carnegie Mellon University, United States"},
    {"name": "Justin Hsu", "affiliation": "Cornell University, United States"},
    {"name": "Atsushi Igarashi", "affiliation": "Kyoto University, Japan"},
    {"name": "Ranjit Jhala", "affiliation": "University of California at San Diego, United States"},
    {"name": "Benjamin Lucien Kaminski", "affiliation": "Saarland University and University College London, Germany"},
    {"name": "Shin-ya Katsumata", "affiliation": "National Institute of Informatics, Japan"},
    {"name": "Alex Kavvos", "affiliation": "University of Bristol, United Kingdom"},
    {"name": "Andrew Kennedy", "affiliation": "Facebook London, United Kingdom"},
    {"name": "Neel Krishnaswami", "affiliation": "University of Cambridge, United Kingdom"},
    {"name": "Ori Lahav", "affiliation": "Tel Aviv University, Israel"},
    {"name": "Leonidas Lampropoulos", "affiliation": "University of Maryland, College Park, Greece"},
    {"name": "Woosuk Lee", "affiliation": "Hanyang University, South Korea"},
    {"name": "Hongjin Liang", "affiliation": "Nanjing University, China"},
    {"name": "Anthony Widjaja Lin", "affiliation": "TU Kaiserslautern; MPI-SWS, Germany"},
    {"name": "Fan Long", "affiliation": "University of Toronto, Canada"},
    {"name": "P. Madhusudan", "affiliation": "University of Illinois at Urbana-Champaign, United States"},
    {"name": "Kenneth L. McMillan", "affiliation": "University of Texas at Austin, United States"},
    {"name": "J. Garrett Morris", "affiliation": "The University of Iowa, United States"},
    {"name": "Koko Muroya", "affiliation": "RIMS, Kyoto University, Japan"},
    {"name": "C.-H. Luke Ong", "affiliation": "University of Oxford, United Kingdom"},
    {"name": "Pavel Panchekha", "affiliation": "University of Utah, United States"},
    {"name": "Matthew J. Parkinson", "affiliation": "Microsoft Research, UK, United Kingdom"},
    {"name": "François Pottier", "affiliation": "Inria, France"},
    {"name": "Philipp Ruemmer", "affiliation": "Uppsala University, Sweden"},
    {"name": "Chung-chieh Shan", "affiliation": "Indiana University, USA"},
    {"name": "Filip Sieczkowski", "affiliation": "University of Wrocław, Poland"},
    {"name": "Bas Spitters", "affiliation": "Aarhus University, Denmark"},
    {"name": "Sam Staton", "affiliation": "University of Oxford"},
    {"name": "Kohei Suenaga", "affiliation": "Graduate School of Informatics, Kyoto University, Japan"},
    {"name": "Tachio Terauchi", "affiliation": "Waseda University, Japan"},
    {"name": "Aditya V. Thakur", "affiliation": "University of California at Davis, United States"},
    {"name": "Caterina Urban", "affiliation": "INRIA & École Normale Supérieure | Université PSL, France"},
    {"name": "Niki Vazou", "affiliation": "IMDEA Software Institute"},
    {"name": "Dimitrios Vytiniotis", "affiliation": "DeepMind, United Kingdom"},
    {"name": "John Wickerson", "affiliation": "Imperial College London, United Kingdom"},
    {"name": "James R. Wilcox", "affiliation": "Certora, United States"},
    {"name": "Nicolas Wu", "affiliation": "Imperial College London, United Kingdom"},
    {"name": "Qirun Zhang", "affiliation": "Georgia Institute of Technology, United States"},
{"name": "Rajeev Alur", "affiliation": "University of Pennsylvania, General Chair"},
    {"name": "Hongseok Yang", "affiliation": "KAIST, South Korea, PC Chair"},
    {"name": "Nate Foster", "affiliation": "Cornell University, United States, Industrial Relations"},
    {"name": "Loris D'Antoni", "affiliation": "University of Wisconsin-Madison, USA, Publicity Chair"},
    {"name": "Ruzica Piskac", "affiliation": "Yale University, United States, Workshops Co-Chair"},
    {"name": "Ilya Sergey", "affiliation": "National University of Singapore, Singapore, Workshops Co-Chair"},
    {"name": "Jeehoon Kang", "affiliation": "KAIST, South Korea, Student Research Competition Co-Chair"},
    {"name": "Azalea Raad", "affiliation": "Imperial College London, United Kingdom, Student Research Competition Co-Chair"},
    {"name": "Pavel Panchekha", "affiliation": "University of Utah, United States, Artifact Evaluation Co-Chair"},
    {"name": "Mukund Raghothaman", "affiliation": "University of Southern California, Artifact Evaluation Co-Chair"},
    {"name": "Amin Timany", "affiliation": "Aarhus University, Denmark, Web Co-Chair"},
    {"name": "Yuepeng Wang", "affiliation": "Simon Fraser University, Web Co-Chair"},
    {"name": "Konstantinos Kallas", "affiliation": "University of Pennsylvania, Student Volunteer Co-Chair"},
    {"name": "Aaron Weiss", "affiliation": "Northeastern University, United States, Student Volunteer Co-Chair"},
    {"name": "Adam Chlipala", "affiliation": "Massachusetts Institute of Technology, United States, Virtualization Co-Chair"},
    {"name": "Youyou Cong", "affiliation": "Tokyo Institute of Technology, Japan, Virtualization Co-Chair"},
    {"name": "Jennifer Paykin", "affiliation": "Galois, Inc., United States, Accessibility, Diversity and Inclusion Chair"},
    {"name": "Apoorv Ingle", "affiliation": "University of Iowa, United States, Video Chair"}
]

popl_2021 = [
    {"name": "Azadeh Farzan", "affiliation": "University of Toronto, Canada, PC Chair"},
    {"name": "Parosh Aziz Abdulla", "affiliation": "Uppsala University, Sweden"},
    {"name": "Umut A. Acar", "affiliation": "Carnegie Mellon University"},
    {"name": "Nada Amin", "affiliation": "Harvard University, United States"},
    {"name": "Mohamed Faouzi Atig", "affiliation": "Uppsala University, Sweden"},
    {"name": "Mark Batty", "affiliation": "University of Kent, United Kingdom"},
    {"name": "Josh Berdine", "affiliation": "Facebook"},
    {"name": "Annette Bieniusa", "affiliation": "Technische Universität Kaiserslautern, Germany"},
    {"name": "Ahmed Bouajjani", "affiliation": "IRIF, Université Paris Diderot, France"},
    {"name": "William J. Bowman", "affiliation": "University of British Columbia, Canada"},
    {"name": "Pavol Cerny", "affiliation": "TU Wien, Austria"},
    {"name": "Sheng Chen", "affiliation": "University of Louisiana at Lafayette"},
    {"name": "Adam Chlipala", "affiliation": "Massachusetts Institute of Technology, United States"},
    {"name": "Ravi Chugh", "affiliation": "University of Chicago"},
    {"name": "Loris D'Antoni", "affiliation": "University of Wisconsin-Madison, USA"},
    {"name": "Marco Gaboardi", "affiliation": "Boston University, United States"},
    {"name": "Pierre Ganty", "affiliation": "IMDEA Software Institute, Spain"},
    {"name": "Deepak Garg", "affiliation": "Max Planck Institute for Software Systems, Germany"},
    {"name": "Laure Gonnord", "affiliation": "University of Lyon & LIP, France"},
    {"name": "Ichiro Hasuo", "affiliation": "National Institute of Informatics, Japan"},
    {"name": "Matthias Heizmann", "affiliation": "University of Freiburg, Germany"},
    {"name": "Bart Jacobs", "affiliation": "imec-DistriNet, Dept. CS, KU Leuven, Belgium"},
    {"name": "Somesh Jha", "affiliation": "University of Wisconsin, Madison, United States"},
    {"name": "Jeehoon Kang", "affiliation": "KAIST, South Korea"},
    {"name": "Zachary Kincaid", "affiliation": "Princeton University, USA"},
    {"name": "Naoki Kobayashi", "affiliation": "University of Tokyo, Japan"},
    {"name": "Laura Kovacs", "affiliation": "Vienna University of Technology (TU Wien), Austria"},
    {"name": "Dexter Kozen", "affiliation": "Cornell University, United States"},
    {"name": "Rupak Majumdar", "affiliation": "MPI-SWS"},
    {"name": "Luc Maranget", "affiliation": "Inria Paris, France"},
    {"name": "Roland Meyer", "affiliation": "TU Braunschweig"},
    {"name": "David Monniaux", "affiliation": "Grenoble Alps University / CNRS / Grenoble INP / VERIMAG"},
    {"name": "Kedar Namjoshi", "affiliation": "Nokia Bell Labs, United States"},
    {"name": "Andreas Pavlogiannis", "affiliation": "Aarhus University, Denmark"},
    {"name": "Simon Peyton Jones", "affiliation": "Microsoft, UK"},
    {"name": "Frank Pfenning", "affiliation": "Carnegie Mellon University, USA"},
    {"name": "Nadia Polikarpova", "affiliation": "University of California at San Diego"},
    {"name": "Arjun Radhakrishna", "affiliation": "Microsoft"},
    {"name": "Aseem Rastogi", "affiliation": "Microsoft Research, India"},
    {"name": "Sriram Sankaranarayanan", "affiliation": "University of Colorado, Boulder, United States"},
    {"name": "Alan Schmitt", "affiliation": "Inria, France"},
    {"name": "Taro Sekiyama", "affiliation": "National Institute of Informatics, Japan"},
    {"name": "Zhong Shao", "affiliation": "Yale University"},
    {"name": "Rahul Sharma", "affiliation": "Microsoft Research"},
    {"name": "Rishabh Singh", "affiliation": "Google Brain, United States"},
    {"name": "Ana Sokolova", "affiliation": "University of Salzburg, Austria"},
    {"name": "Matthieu Sozeau", "affiliation": "Inria, France"},
    {"name": "Viktor Vafeiadis", "affiliation": "MPI-SWS, Germany"},
    {"name": "David Van Horn", "affiliation": "University of Maryland, USA"},
    {"name": "Nobuko Yoshida", "affiliation": "Imperial College London"},
    {"name": "Santiago Zanella-Béguelin", "affiliation": "Microsoft Research, Cambridge, United Kingdom"},
    {"name": "Damien Zufferey", "affiliation": "MPI-SWS"},
{"name": "Andreas Podelski", "affiliation": "University of Freiburg, Germany, General Chair"},
    {"name": "Azadeh Farzan", "affiliation": "University of Toronto, Canada, Program Chair"},
    {"name": "Fritz Henglein", "affiliation": "Department of Computer Science, University of Copenhagen (DIKU) and Deon Digital, Local Arrangements Chair"},
    {"name": "Nate Foster", "affiliation": "Cornell University, United States, Industrial Relations"},
    {"name": "Jan Hoffmann", "affiliation": "Carnegie Mellon University, United States, Workshops Co-Chair"},
    {"name": "Ruzica Piskac", "affiliation": "Yale University, USA, Workshops Co-Chair"},
    {"name": "Ori Lahav", "affiliation": "Tel Aviv University, Student Research Competition Co-Chair"},
    {"name": "Azalea Raad", "affiliation": "Imperial College London, Student Research Competition Co-Chair"},
    {"name": "Jeehoon Kang", "affiliation": "KAIST, South Korea, Artifact Evaluation Co-Chair"},
    {"name": "Pavel Panchekha", "affiliation": "University of Utah, United States, Artifact Evaluation Co-Chair"},
    {"name": "Hsiang-Shang ‘Josh’ Ko", "affiliation": "Institute of Information Science, Academia Sinica, Taiwan, Web Chair"},
    {"name": "Amin Timany", "affiliation": "Aarhus University, Denmark, Web Chair"},
    {"name": "Michael Greenberg", "affiliation": "Pomona College, Publicity Chair and Virtualization Chair"},
    {"name": "Alexandra Silva", "affiliation": "University College London, United Kingdom, Accessibility Chair"},
    {"name": "Hanneli Tavante", "affiliation": "McGill University, Student Volunteer Co-Chair"},
    {"name": "Aaron Weiss", "affiliation": "Northeastern University, United States, Student Volunteer Co-Chair"},
    {"name": "Harrison Goldstein", "affiliation": "University of Pennsylvania, United States, Social Co-Chair"},
    {"name": "Ilya Sergey", "affiliation": "Yale-NUS College and National University of Singapore, Singapore, Social Co-Chair"}

]

popl_2020 = [
    {"name": "Brigitte Pientka", "affiliation": "McGill University, General Chair"},
    {"name": "Lars Birkedal", "affiliation": "Aarhus University, Program Chair"},
    {"name": "Leif Andersen", "affiliation": "Northeastern University, USA, Video Chair"},
    {"name": "Benjamin Chung", "affiliation": "Northeastern University, Video Chair"},
    {"name": "Benjamin Delaware", "affiliation": "Purdue University, Artifact Evaluation Co-Chair"},
    {"name": "Nate Foster", "affiliation": "Cornell University, United States, Industrial Relations Co-Chair"},
    {"name": "Michael Greenberg", "affiliation": "Pomona College, Publicity Chair"},
    {"name": "Jan Hoffmann", "affiliation": "Carnegie Mellon University, United States, Workshops Co-Chair"},
    {"name": "Kristoffer Just Arndal Andersen", "affiliation": "Aarhus University, Technical Support"},
    {"name": "Jeehoon Kang", "affiliation": "KAIST, South Korea, Artifact Evaluation Co-Chair"},
    {"name": "Zachary Kincaid", "affiliation": "Princeton University, United States, Workshops Co-Chair"},
    {"name": "Hsiang-Shang ‘Josh’ Ko", "affiliation": "Institute of Information Science, Academia Sinica, Taiwan, Web Chair"},
    {"name": "Ori Lahav", "affiliation": "Tel Aviv University, Student Research Competition Co-Chair"},
    {"name": "Carole Mann", "affiliation": "R.S.L, Registration"},
    {"name": "Michael Mislove", "affiliation": "Tulane, Local Chair"},
    {"name": "Carlos Mão de Ferro", "affiliation": "Lasige / Faculty of Sciences, Universidade de Lisboa, Student Volunteer Co-Chair"},
    {"name": "Annabel Satin", "affiliation": "P.C.K, Treasurer & Conference Manager"},
    {"name": "Alexandra Silva", "affiliation": "University College London, United Kingdom, Accessibility Chair"},
    {"name": "Hanneli Tavante", "affiliation": "McGill University, Student Volunteer Co-Chair"},
    {"name": "Amin Timany", "affiliation": "imec-Distrinet KU-Leuven, Web Chair"},
    {"name": "Niki Vazou", "affiliation": "IMDEA Software Institute, Student Research Competition Co-Chair"},
    {"name": "David Walker", "affiliation": "Princeton University, United States, Industrial Relations Co-Chair"},
{"name": "Lars Birkedal", "affiliation": "Aarhus University, PC Chair"},
    {"name": "Alastair F. Donaldson", "affiliation": "Imperial College London, United Kingdom"},
    {"name": "Alexandra Silva", "affiliation": "University College London, United Kingdom"},
    {"name": "Alexey Gotsman", "affiliation": "IMDEA Software Institute, Spain"},
    {"name": "Andrej Bauer", "affiliation": "University of Ljubljana, Slovenia"},
    {"name": "Andrew W. Appel", "affiliation": "Princeton, United States"},
    {"name": "Andrzej Murawski", "affiliation": "University of Oxford, United Kingdom"},
    {"name": "Arjun Guha", "affiliation": "University of Massachusetts Amherst, United States"},
    {"name": "Armando Solar-Lezama", "affiliation": "Massachusetts Institute of Technology, United States"},
    {"name": "Arthur Azevedo de Amorim", "affiliation": "Carnegie Mellon University, USA, United States"},
    {"name": "Arthur Charguéraud", "affiliation": "Inria, France"},
    {"name": "Azalea Raad", "affiliation": "MPI-SWS, Germany, United Kingdom"},
    {"name": "Beta Ziliani", "affiliation": "FAMAF, UNC and CONICET, Argentina"},
    {"name": "Bor-Yuh Evan Chang", "affiliation": "University of Colorado Boulder | Amazon"},
    {"name": "Cédric Fournet", "affiliation": "Microsoft Research"},
    {"name": "Cezara Drăgoi", "affiliation": "INRIA, ENS, CNRS, France"},
    {"name": "Christine Tasson", "affiliation": "University Paris Diderot"},
    {"name": "Chung-Kil Hur", "affiliation": "Seoul National University, Korea, South"},
    {"name": "Colin Gordon", "affiliation": "Drexel University, United States"},
    {"name": "Dominique Devriese", "affiliation": "Vrije Universiteit Brussel, Belgium"},
    {"name": "Eran Yahav", "affiliation": "Technion, Israel"},
    {"name": "Eric Koskinen", "affiliation": "Stevens Institute of Technology"},
    {"name": "Filippo Bonchi", "affiliation": "University of Pisa"},
    {"name": "Francesco Ranzato", "affiliation": "University of Padova, Italy"},
    {"name": "Hiroshi Unno", "affiliation": "University of Tsukuba, Japan"},
    {"name": "Jeffrey S. Foster", "affiliation": "Tufts University, United States"},
    {"name": "Jeremy G. Siek", "affiliation": "Indiana University, USA, United States"},
    {"name": "Jesper Cockx", "affiliation": "TU Delft, Netherlands"},
    {"name": "Limin Jia", "affiliation": "Carnegie Mellon University, United States"},
    {"name": "Magnus O. Myreen", "affiliation": "Chalmers University of Technology, Sweden"},
    {"name": "Margus Veanes", "affiliation": "Microsoft Research"},
    {"name": "Matteo Cimini", "affiliation": "University of Massachusetts Lowell, United States"},
    {"name": "Mirco Tribastone", "affiliation": "IMT Institute for Advanced Studies Lucca, Italy"},
    {"name": "Mohsen Lesani", "affiliation": "University of California, Riverside"},
    {"name": "Noam Rinetzky", "affiliation": "Tel Aviv University, Israel"},
    {"name": "Ohad Kammar", "affiliation": "University of Edinburgh, United Kingdom"},
    {"name": "Osbert Bastani", "affiliation": "University of Pennsylvania, United States"},
    {"name": "Peter Thiemann", "affiliation": "University of Freiburg, Germany"},
    {"name": "Pierre-Yves Strub", "affiliation": "Ecole Polytechnique, France"},
    {"name": "Radha Jagadeesan", "affiliation": "DePaul University"},
    {"name": "Rastislav Bodík", "affiliation": "University of Washington, United States"},
    {"name": "Roopsha Samanta", "affiliation": "Purdue University"},
    {"name": "Sam Lindley", "affiliation": "The University of Edinburgh and Imperial College London, United Kingdom"},
    {"name": "Sandrine Blazy", "affiliation": "Univ Rennes- IRISA, France"},
    {"name": "Shuvendu K. Lahiri", "affiliation": "Microsoft Research"},
    {"name": "Steve Zdancewic", "affiliation": "University of Pennsylvania, United States"},
    {"name": "Sukyoung Ryu", "affiliation": "KAIST, South Korea"},
    {"name": "Susmit Sarkar", "affiliation": "University of St. Andrews"},
    {"name": "Sylvie Putot", "affiliation": "École Polytechnique"},
    {"name": "Thomas Wies", "affiliation": "New York University"},
    {"name": "Tiark Rompf", "affiliation": "Purdue University, United States"},
    {"name": "Ugo Dal Lago", "affiliation": "University of Bologna, Italy / Inria, France, Italy"},
    {"name": "Vijay Ganesh", "affiliation": "Georgia Institute of Technology, United States"},
    {"name": "Xavier Rival", "affiliation": "INRIA/CNRS/ENS Paris, France"}

]

popl_2019 = [
    {"name": "Fritz Henglein", "affiliation": "Department of Computer Science, University of Copenhagen (DIKU), Denmark, General Chair"},
    {"name": "Benjamin Delaware", "affiliation": "Purdue University, Artifact Evaluation Co-Chair"},
    {"name": "Marco Gaboardi", "affiliation": "University at Buffalo, SUNY, United States, Workshops Co-Chair"},
    {"name": "Michael Greenberg", "affiliation": "Pomona College, Publicity Chair"},
    {"name": "Cătălin Hriţcu", "affiliation": "Inria Paris, Artifact Evaluation Co-Chair"},
    {"name": "Zachary Kincaid", "affiliation": "Princeton University, United States, Workshops Co-Chair"},
    {"name": "Hsiang-Shang ‘Josh’ Ko", "affiliation": "National Institute of Informatics, Japan, Website Chair, Taiwan"},
    {"name": "Carole Mann", "affiliation": "R.S.L, Registration"},
    {"name": "Carlos Mão de Ferro", "affiliation": "LASIGE, Faculty of Sciences, University of Lisbon, Portugal, Student Volunteer Co-Captain"},
    {"name": "Alex Sanchez-Stern", "affiliation": "University of California, San Diego, United States, Student Volunteer Co-Captain"},
    {"name": "Annabel Satin", "affiliation": "P.C.K., Conference Coordinator, Treasurer"},
    {"name": "Vasco T. Vasconcelos", "affiliation": "LASIGE, Faculty of Sciences, University of Lisbon, Portugal, Local Arrangements Chair"},
    {"name": "Niki Vazou", "affiliation": "IMDEA Software Institute, Student Research Competition Chair"},
    {"name": "David Walker", "affiliation": "Princeton University, United States, Industrial Relations Chair"},
    {"name": "Stephanie Weirich", "affiliation": "University of Pennsylvania, USA, Program Chair"},
    {"name": "Jakub Zalewski", "affiliation": "Video Chair"},
{"name": "Aaron Stump", "affiliation": "The University of Iowa, USA, United States"},
    {"name": "Alan Jeffrey", "affiliation": "Mozilla Research, United States"},
    {"name": "Andreas Abel", "affiliation": "Gothenburg University, Sweden"},
    {"name": "Andreas Podelski", "affiliation": "University of Freiburg, Germany, Germany"},
    {"name": "Andrew Tolmach", "affiliation": "Portland State University"},
    {"name": "Aws Albarghouthi", "affiliation": "University of Wisconsin-Madison"},
    {"name": "Benjamin Delaware", "affiliation": "Purdue University"},
    {"name": "Claudio Russo", "affiliation": "Microsoft Research"},
    {"name": "Danel Ahman", "affiliation": "University of Ljubljana, Slovenia"},
    {"name": "David Naumann", "affiliation": "Stevens Institute of Technology"},
    {"name": "Dimitrios Vytiniotis", "affiliation": "Microsoft Research, Cambridge"},
    {"name": "Dominic Orchard", "affiliation": "University of Kent, UK, United Kingdom"},
    {"name": "Gabriel Scherer", "affiliation": "INRIA Saclay, France"},
    {"name": "Gavin Bierman", "affiliation": "Oracle Labs, United Kingdom"},
    {"name": "Heather Miller", "affiliation": "Carnegie Mellon University"},
    {"name": "Hongjin Liang", "affiliation": "Nanjing University, China, China"},
    {"name": "Hugo Herbelin", "affiliation": "Ichiro Hasuo, National Institute of Informatics, Japan, Japan"},
    {"name": "Ilya Sergey", "affiliation": "Yale-NUS College and National University of Singapore, Singapore"},
    {"name": "Jacques Garrigue", "affiliation": "Nagoya University, Japan"},
    {"name": "Jan Hoffmann", "affiliation": "Carnegie Mellon University, United States"},
    {"name": "Jean-Philippe Bernardy", "affiliation": "University of Gothenburg"},
    {"name": "June Andronick", "affiliation": "Data61,CSIRO (formerly NICTA) and UNSW, Australia"},
    {"name": "Justin Hsu", "affiliation": "University of Wisconsin-Madison, USA, United States"},
    {"name": "P. Madhusudan", "affiliation": "University of Illinois at Urbana-Champaign, United States"},
    {"name": "Martin Erwig", "affiliation": "Oregon State University, United States"},
    {"name": "Matthew J. Parkinson", "affiliation": "Microsoft Research, UK, United Kingdom"},
    {"name": "Mayur Naik", "affiliation": "University of Pennsylvania"},
    {"name": "Michael D. Adams", "affiliation": "University of Utah, United States"},
    {"name": "Michael Emmi", "affiliation": "SRI International, United States"},
    {"name": "Michael Greenberg", "affiliation": "Pomona College"},
    {"name": "Nate Foster", "affiliation": "Cornell University, United States"},
    {"name": "Nicolas Tabareau", "affiliation": "Inria, France"},
    {"name": "Nikhil Swamy", "affiliation": "Microsoft Research, United States"},
    {"name": "Niki Vazou", "affiliation": "IMDEA Software Institute"},
    {"name": "Nils Anders Danielsson", "affiliation": "University of Gothenburg, Chalmers University of Technology"},
    {"name": "Noam Zeilberger", "affiliation": "University of Birmingham, UK"},
    {"name": "Ori Lahav", "affiliation": "Tel Aviv University"},
    {"name": "Patricia Johann", "affiliation": "Appalachian State University"},
    {"name": "Peter O'Hearn", "affiliation": "Facebook"},
    {"name": "Peter Selinger", "affiliation": "Dalhaousie University"},
    {"name": "Radu Grigore", "affiliation": "University of Kent, United Kingdom"},
    {"name": "Robbert Krebbers", "affiliation": "Delft University of Technology, Netherlands"},
    {"name": "Robert Atkey", "affiliation": "University of Strathclyde"},
    {"name": "Ryan R. Newton", "affiliation": "Indiana University, United States"},
    {"name": "Sam Tobin-Hochstadt", "affiliation": "Indiana University, United States"},
    {"name": "Scott Owens", "affiliation": "University of Kent, UK, United Kingdom"},
    {"name": "Suresh Jagannathan", "affiliation": "Purdue University"},
    {"name": "Swarat Chaudhuri", "affiliation": "Rice University"},
    {"name": "Zhenjiang Hu", "affiliation": "National Institute of Informatics, Japan"},
    {"name": "Matthew Hammer", "affiliation": "None, United States"},
    {"name": "Stephanie Weirich", "affiliation": "University of Pennsylvania, USA, United States"}
]

pldi_2023 = [
    {"name": "Steve Blackburn", "affiliation": "Google and Australian National University, Australia"},
    {"name": "Nate Foster", "affiliation": "Cornell University, United States"},
    {"name": "Manuel Rigger", "affiliation": "National University of Singapore, Singapore"},
    {"name": "Xinyu Wang", "affiliation": "University of Michigan, United States"},
    {"name": "Madan Musuvathi", "affiliation": "Microsoft Research"},
    {"name": "Fernando Magno Quintão Pereira", "affiliation": "Federal University of Minas Gerais, Brazil"},
    {"name": "William J. Bowman", "affiliation": "University of British Columbia, Canada"},
    {"name": "Anders Miltner", "affiliation": "Simon Fraser University, United States"},
    {"name": "Rachit Nigam", "affiliation": "Cornell University, United States"},
    {"name": "Alex Renda", "affiliation": "Massachusetts Institute of Technology, United States"},
    {"name": "Sasa Misailovic", "affiliation": "University of Illinois at Urbana-Champaign, United States"},
    {"name": "Deian Stefan", "affiliation": "University of California at San Diego, United States"},
    {"name": "Chandrakana Nandi", "affiliation": "Certora, United States"},
    {"name": "Jubi Taneja", "affiliation": "Microsoft Research, United States"},
    {"name": "Zixian Cai", "affiliation": "Australian National University, Australia"},
    {"name": "Guilherme Espada", "affiliation": "LASIGE, University of Lisbon, Portugal"},
    {"name": "John Hui", "affiliation": "Columbia University, New York, United States"},
    {"name": "Michael B. James", "affiliation": "University of California at San Diego, United States"},
    {"name": "Hanneli Tavante", "affiliation": "Unaffiliated"},
    {"name": "Dan Barowy", "affiliation": "Williams College, United States"},
    {"name": "Jedidiah McClurg", "affiliation": "Colorado State University, United States"},
    {"name": "Nadia Polikarpova", "affiliation": "University of California at San Diego, United States"},
    {"name": "Zachary Tatlock", "affiliation": "University of Washington, United States"},
    {"name": "Nate Foster", "affiliation": "Cornell University, United States"},
    {"name": "Vinod Grover", "affiliation": "NVIDIA, United States"},
    {"name": "Matthias Hauswirth", "affiliation": "USI Lugano, Switzerland"},
    {"name": "Michael Hicks", "affiliation": "Amazon Web Services and the University of Maryland, United States"},
    {"name": "Shan Lu", "affiliation": "University of Chicago, United States"},
    {"name": "Sukyoung Ryu", "affiliation": "KAIST, South Korea"},
    {"name": "John Regehr", "affiliation": "University of Utah"},
    {"name": "Adam Chlipala", "affiliation": "Massachusetts Institute of Technology, United States"},
    {"name": "Benjamin Delaware", "affiliation": "Purdue University, United States"},
    {"name": "Christos Dimoulas", "affiliation": "PLT @ Northwestern University, United States"},
    {"name": "Eric Eide", "affiliation": "University of Utah, United States"},
    {"name": "Andreas Rossberg", "affiliation": "Independent, Germany"},
    {"name": "Michelle Mills Strout", "affiliation": "Hewlett Packard Enterprise"},
    {"name": "Parosh Aziz Abdulla", "affiliation": "Uppsala University, Sweden"},
    {"name": "Umut A. Acar", "affiliation": "Carnegie Mellon University, United States"},
    {"name": "Jade Alglave", "affiliation": "University College London, France"},
    {"name": "Jason Ansel", "affiliation": "Meta, United States"},
    {"name": "Sotiris Apostolakis", "affiliation": "Google, United States"},
    {"name": "Dan Barowy", "affiliation": "Williams College, United States"},
    {"name": "Ryan Beckett", "affiliation": "Microsoft Research, USA"},
    {"name": "Walter Binder", "affiliation": "USI Lugano, Switzerland"},
    {"name": "Rastislav Bodík", "affiliation": "Google Research, Brain Team, United States"},
    {"name": "Michael D. Bond", "affiliation": "Ohio State University, USA"},
    {"name": "Mihai Budiu", "affiliation": "VMware Research Group"},
    {"name": "Calin Cascaval", "affiliation": "Google Research, New Zealand"},
    {"name": "Satish Chandra", "affiliation": "Meta Platforms, United States"},
    {"name": "Swarat Chaudhuri", "affiliation": "University of Texas at Austin, United States"},
    {"name": "James Cheney", "affiliation": "University of Edinburgh, United Kingdom"},
    {"name": "Stephen Chong", "affiliation": "Harvard University, United States"},
    {"name": "Loris D'Antoni", "affiliation": "University of Wisconsin-Madison, United States"},
    {"name": "Yaniv David", "affiliation": "Columbia University, United States"},
    {"name": "Brian Demsky", "affiliation": "University of California at Irvine"},
    {"name": "Dana Drachsler Cohen", "affiliation": "Technion, Israel"},
    {"name": "Kevin Ellis", "affiliation": "Cornell University, United States"},
    {"name": "Xinyu Feng", "affiliation": "Nanjing University, China"},
    {"name": "Irene Finocchi", "affiliation": "Luiss Guido Carli, Italy"},
    {"name": "Alcides Fonseca", "affiliation": "University of Lisbon, Portugal"},
    {"name": "Zhoulai Fu", "affiliation": "State University of New York, Korea"},
    {"name": "François Gauthier", "affiliation": "Oracle Labs, Australia"},
    {"name": "Paul Gazzillo", "affiliation": "University of Central Florida, United States"},
    {"name": "Pierre Geneves", "affiliation": "CNRS/LIG, France"},
    {"name": "Guy Gueta", "affiliation": "VMWare"},
    {"name": "Sam Guyer", "affiliation": "Tufts University, United States"},
    {"name": "Kihong Heo", "affiliation": "KAIST, South Korea"},
    {"name": "Josiah Hester", "affiliation": "Georgia Institute of Technology, United States"},
    {"name": "Jan Hoffmann", "affiliation": "Carnegie Mellon University, United States"},
    {"name": "Chung-Kil Hur", "affiliation": "Seoul National University, South Korea"},
    {"name": "Limin Jia", "affiliation": "Carnegie Mellon University"},
    {"name": "Alexandra Jimborean", "affiliation": "University of Murcia, Spain"},
    {"name": "Gowtham Kaki", "affiliation": "University of Colorado Boulder, United States"},
    {"name": "Fredrik Kjolstad", "affiliation": "Stanford University, United States"},
    {"name": "Eric Koskinen", "affiliation": "Stevens Institute of Technology, United States"},
    {"name": "Robbert Krebbers", "affiliation": "Radboud University Nijmegen, Netherlands"},
    {"name": "Viktor Kunčak", "affiliation": "EPFL, Switzerland"},
    {"name": "Ori Lahav", "affiliation": "Tel Aviv University, Israel"},
    {"name": "Akash Lal", "affiliation": "Microsoft Research"},
    {"name": "Leonidas Lampropoulos", "affiliation": "University of Maryland, College Park, Greece"},
    {"name": "Owolabi Legunsen", "affiliation": "Cornell University, United States"},
    {"name": "Mohsen Lesani", "affiliation": "University of California at Riverside, United States"},
    {"name": "Yao Li", "affiliation": "Portland State University, United States"},
    {"name": "Yu David Liu", "affiliation": "SUNY Binghamton, United States"},
    {"name": "Alexey Loginov", "affiliation": "Meta, United States"},
    {"name": "Nuno P. Lopes", "affiliation": "INESC-ID; Instituto Superior Técnico - University of Lisbon, Portugal"},
    {"name": "Brandon Lucia", "affiliation": "Carnegie Mellon University, USA"},
    {"name": "Konstantinos Mamouras", "affiliation": "Rice University, United States"},
    {"name": "Jedidiah McClurg", "affiliation": "Colorado State University, United States"},
    {"name": "Maryam Mehri Dehnavi", "affiliation": "University of Toronto, Canada"},
    {"name": "Charith Mendis", "affiliation": "University of Illinois at Urbana-Champaign, United States"},
    {"name": "Dimitris Mitropoulos", "affiliation": "University of Athens, Greece"},
    {"name": "Toby Murray", "affiliation": "University of Melbourne, Australia"},
    {"name": "Magnus O. Myreen", "affiliation": "Chalmers University of Technology"},
    {"name": "Cyrus Omar", "affiliation": "University of Michigan, United States"},
    {"name": "Peter-Michael Osera", "affiliation": "Grinnell College, United States"},
    {"name": "Oded Padon", "affiliation": "VMware Research, United States"},
    {"name": "Zoe Paraskevopoulou", "affiliation": "Northeastern University, United States"},
    {"name": "Hila Peleg", "affiliation": "Technion, Israel"},
    {"name": "Lauren Pick", "affiliation": "University of Wisconsin-Madison and University of California, Berkeley, United States"},
    {"name": "Ruzica Piskac", "affiliation": "Yale University, United States"},
    {"name": "Louis-Noël Pouchet", "affiliation": "Colorado State University, USA"},
    {"name": "Jorge A. Pérez", "affiliation": "University of Groningen, Netherlands"},
    {"name": "Jonathan Ragan-Kelley", "affiliation": "Massachusetts Institute of Technology, United States"},
    {"name": "Mukund Raghothaman", "affiliation": "University of Southern California, United States"},
    {"name": "Veselin Raychev", "affiliation": "DeepCode AG"},
    {"name": "Alastair Reid", "affiliation": "Arm Ltd, United Kingdom"},
    {"name": "Noam Rinetzky", "affiliation": "Tel Aviv University, Israel"},
    {"name": "Cindy Rubio-González", "affiliation": "University of California at Davis, United States"},
    {"name": "Susmit Sarkar", "affiliation": "University of St. Andrews"},
    {"name": "Ilya Sergey", "affiliation": "National University of Singapore, Singapore"},
    {"name": "Thomas Shull", "affiliation": "Oracle Labs"},
    {"name": "Jeremy G. Siek", "affiliation": "Indiana University, USA, United States"},
    {"name": "Gagandeep Singh", "affiliation": "University of Illinois at Urbana-Champaign, United States"},
    {"name": "KC Sivaramakrishnan", "affiliation": "IIT Madras and Tarides, India"},
    {"name": "Gang Tan", "affiliation": "Pennsylvania State University, United States"},
    {"name": "Xulong Tang", "affiliation": "University of Pittsburgh"},
    {"name": "Joseph Tassarotti", "affiliation": "NYU, United States"},
    {"name": "Zachary Tatlock", "affiliation": "University of Washington, United States"},
    {"name": "Sam Tobin-Hochstadt", "affiliation": "Indiana University"},
    {"name": "Jean-Baptiste Tristan", "affiliation": "Amazon Web Services, United States"},
    {"name": "David Van Horn", "affiliation": "University of Maryland, United States"},
    {"name": "Niki Vazou", "affiliation": "IMDEA Software Institute"},
    {"name": "Freek Verbeek", "affiliation": "Open University of the Netherlands, The Netherlands"},
    {"name": "Abhinav Verma", "affiliation": "The Pennsylvania State University"},
    {"name": "Chao Wang", "affiliation": "University of Southern California, United States"},
    {"name": "Ke Wang", "affiliation": "Visa Research, United States"},
    {"name": "James R. Wilcox", "affiliation": "University of Washington, Seattle, United States"},
    {"name": "Ningning Xie", "affiliation": "Google DeepMind / University of Toronto, Canada"},
    {"name": "Yingfei Xiong", "affiliation": "Peking University, China"},
{"name": "Jeremy Yallop", "affiliation": "University of Cambridge, United Kingdom"},
    {"name": "Peisen Yao", "affiliation": "Zhejing University, China"},
    {"name": "Greta Yorsh", "affiliation": "Jane Street"},
    {"name": "Ayal Zaks", "affiliation": "Mobileye"},
    {"name": "Yizhou Zhang", "affiliation": "University of Waterloo, Canada"},
    {"name": "He Zhu", "affiliation": "Rutgers University, USA"}
]

pldi_2022 = [
    {"name": "Ranjit Jhala", "affiliation": "University of California at San Diego; Amazon Web Services, United States"},
    {"name": "Işıl Dillig", "affiliation": "University of Texas at Austin, United States"},
    {"name": "Dan Barowy", "affiliation": "Williams College, United States"},
    {"name": "Matt Bowers", "affiliation": "MIT-CSAIL, United States"},
    {"name": "William J. Bowman", "affiliation": "University of British Columbia, Canada"},
    {"name": "Ravi Chugh", "affiliation": "University of Chicago"},
    {"name": "Guilherme Espada", "affiliation": "LASIGE, Faculdade de Ciências, Universidade de Lisboa, Portugal"},
    {"name": "Dan Grossman", "affiliation": "University of Washington, United States"},
    {"name": "Arjun Guha", "affiliation": "Northeastern University, United States"},
    {"name": "Sasa Misailovic", "affiliation": "University of Illinois at Urbana-Champaign, United States"},
    {"name": "Madan Musuvathi", "affiliation": "Microsoft Research"},
    {"name": "Santosh Nagarakatte", "affiliation": "Rutgers University, United States"},
    {"name": "Rachit Nigam", "affiliation": "Cornell University, United States"},
    {"name": "Nadia Polikarpova", "affiliation": "University of California at San Diego, United States"},
    {"name": "Alexandra Silva", "affiliation": "Cornell University, United States"},
    {"name": "Tyler Sorensen", "affiliation": "University of California at Santa Cruz, United States"},
    {"name": "Jubi Taneja", "affiliation": "Microsoft Research, United States"},
    {"name": "Hanneli Tavante", "affiliation": "McGill University"},
    {"name": "Niki Vazou", "affiliation": "IMDEA Software Institute"},
    {"name": "Xinyu Wang", "affiliation": "University of Michigan, United States"},
{"name": "Niki Vazou", "affiliation": "IMDEA Software Institute"},
    {"name": "Xinyu Wang", "affiliation": "University of Michigan, United States"},
    {"name": "Adithya Murali", "affiliation": "University of Illinois at Urbana-Champaign, United States"},
    {"name": "Adrian Palacios", "affiliation": "Amazon Web Services, Spain"},
    {"name": "Akram El-Korashy", "affiliation": "MPI-SWS"},
    {"name": "Alcides Fonseca", "affiliation": "LASIGE, Faculty of Sciences, University of Lisbon, Portugal"},
    {"name": "Alexandra Bugariu", "affiliation": "ETH Zurich, Switzerland"},
    {"name": "Alexios Voulimeneas", "affiliation": "imec-DistriNet, KU Leuven, Belgium"},
    {"name": "Ali Shokri", "affiliation": "Rochester Institute of Technology, United States"},
    {"name": "Anju M A", "affiliation": "IIT Madras, India"},
    {"name": "Austin Mordahl", "affiliation": "University of Texas at Dallas, United States"},
    {"name": "Benjamin Mariano", "affiliation": "The University of Texas at Austin, Texas, USA, United States"},
    {"name": "Clemens Dubslaff", "affiliation": "TU Dresden, Germany"},
    {"name": "Daming Zou", "affiliation": "ETH Zurich, Switzerland"},
    {"name": "David Moon", "affiliation": "University of Michigan"},
    {"name": "Deivid Vale", "affiliation": "Radboud University, Netherlands"},
    {"name": "Dominik Winterer", "affiliation": "ETH Zurich, Switzerland"},
    {"name": "Dongpeng Xu", "affiliation": "University of New Hampshire, United States"},
    {"name": "Elliott Slaughter", "affiliation": "SLAC National Accelerator Laboratory"},
    {"name": "Goran Piskachev", "affiliation": "Fraunhofer IEM, Germany"},
    {"name": "Guannan Wei", "affiliation": "Purdue University, United States"},
    {"name": "Guilherme Espada", "affiliation": "LASIGE, Faculdade de Ciências, Universidade de Lisboa, Portugal"},
    {"name": "Hailong Zhang", "affiliation": "Fordham University"},
    {"name": "Hendrik Maarand", "affiliation": "Tallinn University of Technology"},
    {"name": "Hernán Ponce de León", "affiliation": "Bundeswehr University Munich, Germany"},
    {"name": "Hongzheng Chen", "affiliation": "Cornell University, United States"},
    {"name": "Hugo Brunie", "affiliation": "INRIA"},
    {"name": "Irene Yoon", "affiliation": "University of Pennsylvania"},
    {"name": "Jason Hemann", "affiliation": "Northeastern University, United States"},
    {"name": "Jialu Bao", "affiliation": "Cornell University"},
    {"name": "Jie Zhou", "affiliation": "University of Rochester, United States"},
    {"name": "Jingbo Wang", "affiliation": "University of Southern California"},
    {"name": "Jingxuan He", "affiliation": "ETH Zurich, Switzerland"},
    {"name": "Jonas Kastberg Hinrichsen", "affiliation": "Aarhus University, Denmark"},
    {"name": "Jules Jacobs", "affiliation": "Radboud University"},
    {"name": "Karine Even-Mendoza", "affiliation": "Imperial College London, United Kingdom"},
    {"name": "Keyur Joshi", "affiliation": "University of Illinois at Urbana-Champaign, United States"},
    {"name": "Larisa Safina", "affiliation": "INRIA Lillle - Nord Europe, France"},
    {"name": "Lars B. van den Haak", "affiliation": "Eindhoven University of Technology, Netherlands"},
    {"name": "Madhukar Kedlaya", "affiliation": "Shape Security, United States"},
    {"name": "Maja Hanne Kirkeby", "affiliation": ""},
    {"name": "Mallku Soldevila", "affiliation": "FAMAF, UNC / CONICET, Argentina"},
    {"name": "Marcos Horro Varela", "affiliation": "Advanced Micro Devices (AMD), Spain"},
    {"name": "Marcos Yukio Siraichi", "affiliation": "The University of Tokyo"},
    {"name": "Maria Bendix Mikkelsen", "affiliation": ""},
    {"name": "Mário Pereira", "affiliation": "NOVA LINCS & DI -- Nova School of Science and Technology"},
    {"name": "Martin Lester", "affiliation": "University of Reading, United Kingdom"},
    {"name": "Maxime Cordy", "affiliation": "University of Luxembourg, Luxembourg"},
    {"name": "Maxi Wuttke", "affiliation": "MPI-SWS, Germany"},
    {"name": "Mehran Alidoost Nia", "affiliation": "University of Tehran, Iran"},
    {"name": "Neea Rusch", "affiliation": "Augusta University, United States"},
    {"name": "Peixin Wang", "affiliation": "University of Oxford"},
    {"name": "Pengbo Yan", "affiliation": "University of Melbourne"},
    {"name": "Phil Nguyen", "affiliation": "Google"},
    {"name": "Pietro Ferrara", "affiliation": "Università Ca' Foscari, Venezia, Italy"},
    {"name": "Quang-Trung Ta", "affiliation": "National University of Singapore"},
    {"name": "Raphaël Monat", "affiliation": "Sorbonne Université — LIP6, France"},
    {"name": "Roberto Blanco", "affiliation": "Max Planck Institute for Security and Privacy (MPI-SP)"},
    {"name": "Shangyin Tan", "affiliation": "Purdue University, United States"},
    {"name": "Shouvick Mondal", "affiliation": "Concordia University, Montreal, Canada"},
    {"name": "Somesh Singh", "affiliation": "INRIA, ENS Lyon, France"},
    {"name": "Stanly Samuel", "affiliation": "Indian Institute of Science, India"},
    {"name": "Stefanos Chaliasos", "affiliation": "Imperial College London, United Kingdom"},
    {"name": "Thodoris Sotiropoulos", "affiliation": "Athens University of Economics and Business, Greece"},
    {"name": "Ton Chanh Le", "affiliation": "Stevens Institute of Technology"},
    {"name": "Utpal Bora", "affiliation": "IIT Hyderabad, India"},
    {"name": "Weixin Zhang", "affiliation": "University of Bristol, UK"},
    {"name": "Wenxi Wang", "affiliation": "University of Texas at Austin, United States"},
    {"name": "Yahui Song", "affiliation": "National University of Singapore, Singapore"},
    {"name": "Yangyu Zhang", "affiliation": "Institute of Computing Technology, Chinese Academy of Sciences, China"},
    {"name": "Yanju Chen", "affiliation": "University of California, Santa Barbara, United States"},
    {"name": "Yanjun Wang", "affiliation": "Purdue University, USA"},
    {"name": "Yann Herklotz", "affiliation": "Imperial College London, United Kingdom"},
    {"name": "Yixuan Chen", "affiliation": "Yale University, USA"},
    {"name": "Yuke Wang", "affiliation": "UC Santa Barbara, United States"},
    {"name": "Yutian Tang", "affiliation": "ShanghaiTech University, China"},
    {"name": "Zheng Guo", "affiliation": "University of California, San Diego"},
    {"name": "Zixian Cai", "affiliation": "Australian National University, Australia"},
    {"name": "Ziyang Xu", "affiliation": "Princeton University, United States"},
    {"name": "Emilio Jesús Gallego Arias", "affiliation": "INRIA, France"},
    {"name": "Alex Gu", "affiliation": "MIT CSAIL, United States"},
    {"name": "Lennard Gäher", "affiliation": "MPI-SWS & Saarland University, Germany"},
    {"name": "Adharsh Kamath", "affiliation": "NITK Surathkal, India"},
    {"name": "Daniel Marshall", "affiliation": "University of Kent, UK, United Kingdom"},
    {"name": "Simon Spies", "affiliation": "MPI-SWS & Saarland University, Germany"},
    {"name": "Pedro da Costa Abreu Junior", "affiliation": "Purdue University"}

]

pldi_2021 = [
    {"name": "Stephen N. Freund", "affiliation": "Williams College"},
    {"name": "Eran Yahav", "affiliation": "Technion"},
    {"name": "Dan Barowy", "affiliation": "Williams College, United States"},
    {"name": "Matt Bowers", "affiliation": "MIT-CSAIL, United States"},
    {"name": "Sarah E. Chasins", "affiliation": "University of California, Berkeley"},
    {"name": "Ravi Chugh", "affiliation": "University of Chicago, United States"},
    {"name": "Dan Grossman", "affiliation": "University of Washington, United States"},
    {"name": "Arjun Guha", "affiliation": "Northeastern University, United States"},
    {"name": "Dan Iorga", "affiliation": "Imperial College London, United Kingdom"},
    {"name": "Stefan Marr", "affiliation": "University of Kent, United Kingdom"},
    {"name": "Rachit Nigam", "affiliation": "Cornell University, USA"},
    {"name": "Luís Pina", "affiliation": "University of Illinois at Chicago, United States"},
    {"name": "Alexandra Silva", "affiliation": "University College London, United Kingdom"},
    {"name": "Tyler Sorensen", "affiliation": "University of California at Santa Cruz"},
    {"name": "Manu Sridharan", "affiliation": "University of California at Riverside, United States"},
    {"name": "Niki Vazou", "affiliation": "IMDEA Software Institute"},
    {"name": "John Wickerson", "affiliation": "Imperial College London, United Kingdom"},
{"name": "Adam Chlipala", "affiliation": "Massachusetts Institute of Technology, United States"},
    {"name": "Aditya Kanade", "affiliation": "Indian Institute of Science, Bangalore"},
    {"name": "Albert Cohen", "affiliation": "Google, France"},
    {"name": "Andreas Rossberg", "affiliation": "Dfinity Stiftung, Germany"},
    {"name": "Andreas Zeller", "affiliation": "CISPA Helmholtz Center for Information Security, Germany"},
    {"name": "Anil Madhavapeddy", "affiliation": "OCaml Labs, United Kingdom"},
    {"name": "Armando Solar-Lezama", "affiliation": "Massachusetts Institute of Technology, United States"},
    {"name": "Ayal Zaks", "affiliation": "Intel Corporation and Technion, Israel"},
    {"name": "Azalea Raad", "affiliation": "Imperial College London, United Kingdom"},
    {"name": "Ben Greenman", "affiliation": "Brown University, United States"},
    {"name": "Ben Hardekopf", "affiliation": "University of California at Santa Barbara, United States"},
    {"name": "Ben Liblit", "affiliation": "Amazon, United States"},
    {"name": "Ben L. Titzer", "affiliation": "Independent Consultant, United States"},
    {"name": "Ben Zorn", "affiliation": "Microsoft"},
    {"name": "Bor-Yuh Evan Chang", "affiliation": "University of Colorado at Boulder; Amazon, United States"},
    {"name": "Brandon Lucia", "affiliation": "Carnegie Mellon University, United States"},
    {"name": "Camil Demetrescu", "affiliation": "Sapienza University Rome, Italy"},
    {"name": "Charlie Curtsinger", "affiliation": "Grinnell College"},
    {"name": "Cindy Rubio-González", "affiliation": "University of California at Davis, United States"},
    {"name": "Cormac Flanagan", "affiliation": "University of California at Santa Cruz"},
    {"name": "Cristian Cadar", "affiliation": "Imperial College London, UK, United Kingdom"},
    {"name": "Danfeng Zhang", "affiliation": "Pennsylvania State University, United States"},
    {"name": "Darko Marinov", "affiliation": "University of Illinois at Urbana-Champaign, United States"},
    {"name": "David I. August", "affiliation": "Princeton University, USA"},
    {"name": "David Darais", "affiliation": "Galois, Inc., United States"},
    {"name": "Doug Lea", "affiliation": "State University of New York (SUNY) Oswego, United States"},
    {"name": "Eran Yahav", "affiliation": "Technion"},
    {"name": "Erez Petrank", "affiliation": "Technion, Israel"},
    {"name": "Eva Darulova", "affiliation": "MPI-SWS, Germany"},
    {"name": "Francesco Logozzo", "affiliation": "Facebook, United States"},
    {"name": "Fredrik Kjolstad", "affiliation": "Stanford University"},
    {"name": "Gagandeep Singh", "affiliation": "VMWare Research and UIUC, United States"},
    {"name": "Gail Kaiser", "affiliation": "Columbia University, United States"},
    {"name": "Gerwin Klein", "affiliation": "CSIRO's Data61 and UNSW Sydney, Australia"},
    {"name": "Görel Hedin", "affiliation": "Lund University, Sweden"},
    {"name": "Grigore Roşu", "affiliation": "University of Illinois at Urbana-Champaign"},
    {"name": "Gustavo Petri", "affiliation": "ARM Research"},
    {"name": "He Zhu", "affiliation": "Rutgers University, USA"},
    {"name": "Heather Miller", "affiliation": "Carnegie Mellon University, USA"},
    {"name": "Hila Peleg", "affiliation": "Technion, Israel"},
    {"name": "Hongseok Yang", "affiliation": "KAIST, South Korea"},
    {"name": "Jan Hoffmann", "affiliation": "Carnegie Mellon University, United States"},
    {"name": "John Sarracino", "affiliation": "University of California, San Diego"},
    {"name": "José Fragoso Santos", "affiliation": "INESC-ID/Instituto Superior Técnico, Portugal"},
    {"name": "Joseph Devietti", "affiliation": "University of Pennsylvania"},
    {"name": "Joxan Jaffar", "affiliation": "National University of Singapore, Singapore"},
    {"name": "Julian Dolby", "affiliation": "IBM Research, USA"},
    {"name": "Julian Shun", "affiliation": "MIT"},
    {"name": "Kapil Vaswani", "affiliation": "Microsoft Research"},
    {"name": "Ke Wang", "affiliation": "Visa Research"},
    {"name": "Kwangkeun Yi", "affiliation": "Seoul National University, South Korea"},
    {"name": "Lindsey Kuper", "affiliation": "University of California at Santa Cruz"},
    {"name": "Loris D'Antoni", "affiliation": "University of Wisconsin-Madison, USA"},
    {"name": "Louis-Noël Pouchet", "affiliation": "Colorado State University, USA"},
    {"name": "Madan Musuvathi", "affiliation": "Microsoft Research"},
    {"name": "Magnus Madsen", "affiliation": "Aarhus University"},
    {"name": "Magnus O. Myreen", "affiliation": "Chalmers University of Technology"},
    {"name": "Mahmut Taylan Kandemir", "affiliation": "Pennsylvania State University, United States"},
    {"name": "Marc Brockschmidt", "affiliation": "Microsoft Research, United Kingdom"},
    {"name": "Markus Püschel", "affiliation": "ETH Zurich, Switzerland"},
    {"name": "Matthew Flatt", "affiliation": "University of Utah, USA"},
    {"name": "Michael D. Bond", "affiliation": "Ohio State University, USA"},
    {"name": "Michael Hicks", "affiliation": "University of Maryland at College Park"},
    {"name": "Michael F. P. O'Boyle", "affiliation": "University of Edinburgh"},
    {"name": "Michael Pradel", "affiliation": "University of Stuttgart, Germany"},
    {"name": "Milind Kulkarni", "affiliation": "Purdue University, United States"},
    {"name": "Na Meng", "affiliation": "Virginia Tech, USA"},
    {"name": "Nate Foster", "affiliation": "Cornell University, United States"},
    {"name": "Nathan Chong", "affiliation": "Amazon, United Kingdom"},
    {"name": "Nikhil Swamy", "affiliation": "Microsoft Research, United States"},
    {"name": "Nikos Vasilakis", "affiliation": "MIT CSAIL, USA, Greece"},
    {"name": "Nuno P. Lopes", "affiliation": "Microsoft Research, United Kingdom"},
    {"name": "Oded Padon", "affiliation": "VMWare Research, United States"},
    {"name": "Osbert Bastani", "affiliation": "University of Pennsylvania, United States"},
    {"name": "Paul Gazzillo", "affiliation": "University of Central Florida, United States"},
    {"name": "Pavel Panchekha", "affiliation": "University of Utah, United States"},
    {"name": "Pavol Bielik", "affiliation": "ETH Zurich, Switzerland"},
    {"name": "Rahul Sharma", "affiliation": "Microsoft Research"},
    {"name": "Ranjit Jhala", "affiliation": "University of California at San Diego"},
    {"name": "Ravi Chugh", "affiliation": "University of Chicago, United States"},
    {"name": "Rishabh Singh", "affiliation": "Google Brain, United States"},
    {"name": "Roopsha Samanta", "affiliation": "Purdue University"},
    {"name": "Ruzica Piskac", "affiliation": "Yale University, USA"},
    {"name": "Ryan R. Newton", "affiliation": "Facebook, United States"},
    {"name": "Sandeep Dasgupta", "affiliation": "Google, USA, United States"},
    {"name": "Sara Achour", "affiliation": "MIT, United States"},
    {"name": "Saswat Padhi", "affiliation": "Amazon Web Services, USA, United States"},
    {"name": "Saumya Debray", "affiliation": "University of Arizona"},
    {"name": "Saurav Muralidharan", "affiliation": "NVIDIA, United States"},
    {"name": "Sebastian Hack", "affiliation": "Saarland University, Germany"},
    {"name": "Simon Peyton Jones", "affiliation": "Microsoft, United Kingdom"},
    {"name": "Sorav Bansal", "affiliation": "IIT Delhi and CompilerAI Labs, India"},
    {"name": "Stephen Kell", "affiliation": "King's College London, United Kingdom"},
    {"name": "Steve Blackburn", "affiliation": "Australian National University, Australia"},
    {"name": "Sukyoung Ryu", "affiliation": "KAIST, South Korea"},
    {"name": "Suresh Jagannathan", "affiliation": "Purdue University, United States"},
    {"name": "Tahina Ramananandro", "affiliation": "Microsoft Research, United States"},
    {"name": "Tamara Rezk", "affiliation": "Inria, France"},
    {"name": "Tatiana Shpeisman", "affiliation": "Google, United States"},
    {"name": "Thomas Reps", "affiliation": "University of Wisconsin, United States"},
    {"name": "Thomas Shull", "affiliation": "Oracle Labs"},
    {"name": "Timon Gehr", "affiliation": "ETH Zurich, Switzerland"},
    {"name": "Ting Cao", "affiliation": "Microsoft Research, China"},
    {"name": "Tobias Wrigstad", "affiliation": "Uppsala University, Sweden"},
    {"name": "Toby Murray", "affiliation": "University of Melbourne, Australia"},
    {"name": "Todd Millstein", "affiliation": "University of California at Los Angeles"},
    {"name": "Tomofumi Yuki", "affiliation": "INRIA"},
    {"name": "Tony Hosking", "affiliation": "Australian National University, Australia"},
    {"name": "Uri Alon", "affiliation": "Technion"},
    {"name": "Vijay Ganesh", "affiliation": "Georgia Tech, United States"},
    {"name": "Viktor Kunčak", "affiliation": "EPFL, Switzerland, Switzerland"},
    {"name": "Viktor Vafeiadis", "affiliation": "MPI-SWS, Germany"},
    {"name": "Vivek Sarkar", "affiliation": "Rice University, United States"},
    {"name": "Willem Visser", "affiliation": "Stellenbosch University, South Africa, South Africa"},
    {"name": "Woosuk Lee", "affiliation": "Hanyang University, South Korea"},
    {"name": "Xinyu Feng", "affiliation": "Nanjing University, China"},
    {"name": "Xinyu Wang", "affiliation": "University of Michigan, United States"},
    {"name": "Xulong Tang", "affiliation": "University of Pittsburgh, United States"},
    {"name": "Yaniv David", "affiliation": "Technion"},
    {"name": "Yannis Smaragdakis", "affiliation": "University of Athens"},
    {"name": "Zachary Tatlock", "affiliation": "University of Washington, Seattle, United States"},
    {"name": "Swarat Chaudhuri", "affiliation": "Rice University"},
    {"name": "Işıl Dillig", "affiliation": "University of Texas at Austin, United States"},
    {"name": "Martin C. Rinard", "affiliation": "Massachusetts Institute of Technology, United States"},
    {"name": "Caitlin Sadowski", "affiliation": "Unknown"},
    {"name": "Xin Zhang", "affiliation": "Peking University, China"}
]

pldi_2020 = [
    {"name": "Alastair F. Donaldson", "affiliation": "Imperial College London, United Kingdom"},
    {"name": "Emina Torlak", "affiliation": "University of Washington, United States"},
    {"name": "Jonathan Bell", "affiliation": "George Mason University, United States"},
    {"name": "Sarah E. Chasins", "affiliation": "University of California, Berkeley"},
    {"name": "Stephen N. Freund", "affiliation": "Williams College, United States"},
    {"name": "Dan Iorga", "affiliation": "Imperial College London, UK, United Kingdom"},
    {"name": "Brandon Lucia", "affiliation": "Carnegie Mellon University, USA"},
    {"name": "Stefan Marr", "affiliation": "University of Kent, United Kingdom"},
    {"name": "Na Meng", "affiliation": "Virginia Tech, United States"},
    {"name": "Luís Pina", "affiliation": "University of Illinois at Chicago, United States"},
    {"name": "Azalea Raad", "affiliation": "Imperial College London, United Kingdom"},
    {"name": "John Renner", "affiliation": "University of California at San Diego, USA"},
    {"name": "Annabel Satin", "affiliation": "P.C.K."},
    {"name": "Manu Sridharan", "affiliation": "University of California Riverside, United States"},
    {"name": "Ross Tate", "affiliation": "Cornell University, United States"},
    {"name": "Ben L. Titzer", "affiliation": "Google, Germany"},
    {"name": "John Wickerson", "affiliation": "Imperial College London, United Kingdom"},
{"name": "Emina Torlak", "affiliation": "University of Washington, United States"},
    {"name": "Aws Albarghouthi", "affiliation": "University of Wisconsin-Madison, USA"},
    {"name": "Dan Barowy", "affiliation": "Williams College, United States"},
    {"name": "Michael D. Bond", "affiliation": "Ohio State University, USA"},
    {"name": "James Bornholt", "affiliation": "University of Texas at Austin, United States"},
    {"name": "Sebastian Burckhardt", "affiliation": "Microsoft Research, Switzerland"},
    {"name": "Michael Carbin", "affiliation": "Massachusetts Institute of Technology, USA"},
    {"name": "Satish Chandra", "affiliation": "Facebook, United States"},
    {"name": "Alvin Cheung", "affiliation": "University of California, Berkeley"},
    {"name": "Işıl Dillig", "affiliation": "University of Texas at Austin, USA"},
    {"name": "Yufei Ding", "affiliation": "UCSB, China"},
    {"name": "Cezara Drăgoi", "affiliation": "INRIA, ENS, CNRS, France"},
    {"name": "Stephen N. Freund", "affiliation": "Williams College, United States"},
    {"name": "Patrice Godefroid", "affiliation": "Microsoft Research, United States"},
    {"name": "Ronghui Gu", "affiliation": "Columbia University, USA"},
    {"name": "Arjun Guha", "affiliation": "Northeastern University"},
    {"name": "Sam Guyer", "affiliation": "Tufts University, United States"},
    {"name": "Peter Hawkins", "affiliation": "Google"},
    {"name": "Shachar Itzhaky", "affiliation": "Technion, Israel, Israel"},
    {"name": "Alexandra Jimborean", "affiliation": "Uppsala University, Sweden"},
    {"name": "Shoaib Kamil", "affiliation": "Adobe"},
    {"name": "Sriram Krishnamoorthy", "affiliation": "Pacific Northwest National Laboratories"},
    {"name": "Akash Lal", "affiliation": "Microsoft Research India, India"},
    {"name": "Fan Long", "affiliation": "University of Toronto, Canada"},
    {"name": "Santosh Nagarakatte", "affiliation": "Rutgers University, USA"},
    {"name": "Klaus Ostermann", "affiliation": "University of Tübingen, Germany"},
    {"name": "Corina S. Pasareanu", "affiliation": "Carnegie Mellon University Silicon Valley, NASA Ames Research Center"},
    {"name": "Phitchaya Mangpo Phothilimthana", "affiliation": "Google"},
    {"name": "Ruzica Piskac", "affiliation": "Yale University, USA"},
    {"name": "Mukund Raghothaman", "affiliation": "University of Southern California"},
    {"name": "Veselin Raychev", "affiliation": "DeepCode AG"},
    {"name": "John Regehr", "affiliation": "University of Utah, United States"},
    {"name": "Adrian Sampson", "affiliation": "Cornell University, USA"},
    {"name": "Chris Seaton", "affiliation": "Shopify, United Kingdom"},
    {"name": "Tyler Sorensen", "affiliation": "Princeton University, United States"},
    {"name": "Michelle Strout", "affiliation": "University of Arizona, United States"},
    {"name": "Petar Tsankov", "affiliation": "ETH Zurich / ChainSecurity, Switzerland"},
    {"name": "Mandana Vaziri", "affiliation": "IBM Research"},
    {"name": "John Vilk", "affiliation": "Stripe, United States"},
    {"name": "Dimitrios Vytiniotis", "affiliation": "DeepMind, United Kingdom"},
    {"name": "Ke Wang", "affiliation": "Visa Research, United States"},
    {"name": "Eran Yahav", "affiliation": "Technion, Israel"},
    {"name": "Qirun Zhang", "affiliation": "Georgia Institute of Technology, USA"}
]

pldi_2019 = [
    {"name": "Kathryn S McKinley", "affiliation": "Google"},
    {"name": "Kathleen Fisher", "affiliation": "Tufts University, USA, United States"},
    {"name": "Ravi Chugh", "affiliation": "University of Chicago"},
    {"name": "Roopsha Samanta", "affiliation": "Purdue University"},
    {"name": "Maria Christakis", "affiliation": "MPI-SWS, Germany"},
    {"name": "Ross Tate", "affiliation": "Cornell University, United States"},
    {"name": "Ben L. Titzer", "affiliation": "Google, Germany"},
    {"name": "Stephen N. Freund", "affiliation": "Williams College, United States"},
    {"name": "Michelle Strout", "affiliation": "University of Arizona, United States"},
    {"name": "Brandon Lucia", "affiliation": "Carnegie Mellon University, United States"},
    {"name": "Minjia Zhang", "affiliation": "Microsoft Research, United States"},
    {"name": "Xujie Si", "affiliation": "University of Pennsylvania"},
    {"name": "Matthias Springer", "affiliation": "Tokyo Institute of Technology, Germany"},
    {"name": "Shoaib Akram", "affiliation": "Ghent University, Belgium"},
    {"name": "Na Meng", "affiliation": "Virginia Tech, United States"},
    {"name": "Annabel Satin", "affiliation": "P.C.K."},
{"name": "Kathleen Fisher", "affiliation": "Tufts University, USA, United States"},
    {"name": "Neha Agarwal", "affiliation": "Google, United States"},
    {"name": "Amal Ahmed", "affiliation": "Northeastern University, USA, United States"},
    {"name": "June Andronick", "affiliation": "Data61,CSIRO (formerly NICTA) and UNSW, Australia"},
    {"name": "Walter Binder", "affiliation": "University of Lugano, Switzerland"},
    {"name": "Camil Demetrescu", "affiliation": "Sapienza University Rome, Italy"},
    {"name": "Alastair F. Donaldson", "affiliation": "Google and Imperial College London, United Kingdom"},
    {"name": "Dana Drachsler Cohen", "affiliation": "ETH Zurich, Switzerland"},
    {"name": "Michael Emmi", "affiliation": "SRI International, United States"},
    {"name": "Xinyu Feng", "affiliation": "Nanjing University, China"},
    {"name": "Michael Greenberg", "affiliation": "Pomona College"},
    {"name": "Guy Gueta", "affiliation": "VMWare Research"},
    {"name": "Martin Hirzel", "affiliation": "IBM Research, United States"},
    {"name": "Chung-Kil Hur", "affiliation": "Seoul National University, Korea, South"},
    {"name": "Suresh Jagannathan", "affiliation": "Purdue University"},
    {"name": "Limin Jia", "affiliation": "Carnegie Mellon University, United States"},
    {"name": "Gabriele Keller", "affiliation": "Utrecht University, Netherlands"},
    {"name": "Shriram Krishnamurthi", "affiliation": "Brown University, United States"},
    {"name": "Neel Krishnaswami", "affiliation": "Computer Laboratory, University of Cambridge"},
    {"name": "Woosuk Lee", "affiliation": "Hanyang University, South Korea"},
    {"name": "Nuno P. Lopes", "affiliation": "Microsoft Research"},
    {"name": "Martin Maas", "affiliation": "Google, United States"},
    {"name": "Kathryn S McKinley", "affiliation": "Google"},
    {"name": "Sasa Misailovic", "affiliation": "University of Illinois at Urbana-Champaign, United States"},
    {"name": "Nadia Polikarpova", "affiliation": "University of California, San Diego, United States"},
    {"name": "Louis-Noël Pouchet", "affiliation": "Colorado State University"},
    {"name": "Michael Pradel", "affiliation": "TU Darmstadt and Facebook, Germany"},
    {"name": "Shaz Qadeer", "affiliation": "Facebook, United States"},
    {"name": "Martin C. Rinard", "affiliation": "Massachusetts Institute of Technology, United States"},
    {"name": "Cindy Rubio-González", "affiliation": "University of California, Davis, United States"},
    {"name": "Jennifer B. Sartor", "affiliation": "Ghent University and Vrije Universiteit Brussel, Belgium"},
    {"name": "Ilya Sergey", "affiliation": "Yale-NUS College, Singapore"},
    {"name": "Zhendong Su", "affiliation": "ETH Zurich, Switzerland"},
    {"name": "Zachary Tatlock", "affiliation": "University of Washington, Seattle, United States"},
    {"name": "Ben L. Titzer", "affiliation": "Google, Germany"},
    {"name": "Emina Torlak", "affiliation": "University of Washington, United States"},
    {"name": "John Wickerson", "affiliation": "Imperial College London, United Kingdom"},
    {"name": "Ayal Zaks", "affiliation": "Intel Corporation and Technion, Israel"},
    {"name": "Eddy (Zheng) Zhang", "affiliation": "Rutgers"}
]



from difflib import SequenceMatcher

def similar(a, b):
    return SequenceMatcher(None, a, b).ratio()

def disambiguate_authors(chairs_list, previous_list):
    disambiguated_list = []
    used_names = set()

    for chair in chairs_list:
        best_match = None
        max_similarity = 0

        for prev_chair in previous_list:
            similarity = similar(chair['name'], prev_chair['name'])
            # print(chair['name'])
            if similarity > max_similarity and chair['affiliation'] == prev_chair['affiliation']:
                max_similarity = similarity
                best_match = prev_chair

        if best_match is not None and best_match['name'] not in used_names:
            disambiguated_list.append(best_match)
            used_names.add(best_match['name'])
        else:
            disambiguated_list.append(chair)

    return disambiguated_list

# Combine all the committee chairs lists
all_chairs = popl_2019+popl_2020+popl_2021+popl_2022+popl_2023+pldi_2019+pldi_2021+pldi_2022+pldi_2020+pldi_2023


# Disambiguate and remove duplicates
unique_chairs = disambiguate_authors(all_chairs, all_chairs)

print(unique_chairs)

import csv

# Specify the filename for the CSV file
csv_filename = 'PL_PC.csv'

# Define the field names for the CSV header
field_names = ['name', 'affiliation']

# Write the data to the CSV file
with open(csv_filename, 'w', newline='', encoding='utf-8') as csvfile:
    writer = csv.DictWriter(csvfile, fieldnames=field_names)

    # Write the header
    writer.writeheader()

    # Write the committee_chairs data
    writer.writerows(unique_chairs)

print(f"The data has been written to {csv_filename}")





